flatcar/mantle

- kola/tests/coretest/cloudinit.go
- platform/api/packet/api.go
There's no need to rename this since coreos-cloudinit is just the name of
the project.
> Change back flatcar-cloudinit to coreos-cloudinit

- kola/tests/etcd/discovery.go
- kola/tests/flannel/flannel.go
- kola/tests/locksmith/locksmith.go
There's no need to rename this since coreos-metadata is just the name of
the project.
> Change back flatcar-metadata to coreos-metadata

- kola/tests/coretest/core.go
This is the HSM-generated one we'll use for GA.
> kola: change update public key hash

- cmd/plume/specs.go
- sdk/download.go
We are now using Flatcar's own GCE account. Switch to the new bucket.
> *: switch GCE bucket name

- cmd/kola/options.go
- cmd/ore/gcloud/gcloud.go
It turns out we had to use the ID, not the Name as shown in the Google
Cloud Console.
> kola,ore: use the right project name

- kola/tests/coretest/core.go
To avoid potential issues with a symlink `/usr/lib/coreos` to `/usr/lib/flatcar`, let's add a simple test `TestSymlinkFlatcar` that checks for the symlink on every Flatcar build.
See also https://github.com/flatcar-linux/coreos-overlay/pull/8
> kola: add TestSymlinkFlatcar to check for a symlink to /usr/lib/flatcar

- kola/tests/docker/docker.go
Flatcar edge 2051.99.1 or newer has the cgroup driver "systemd" instead of "cgroupfs". So we need to also update Kola tests to avoid test failures like:
```
--- FAIL: docker.base (541.40s)
--- FAIL: docker.base/docker-info (12.17s)
docker.go:575: unexpected cgroup driver systemd
```
> kola: check also for the systemd cgroup driver

- kola/tests/misc/network.go
Now that containerd listens on `127.0.0.1:10010`, we need to add TCP port 10010 to the listeners, to be able to avoid the following error during `os/kola/qemu` for Flatcar edge builds:
```
network.go:137: Unexpected listener process:
"tcp        0 0 127.0.0.1:10010         0.0.0.0:*               LISTEN 678/containerd"
```
> kola/tests/misc: add TCP port 10010 to listeners for containerd

- platform/qemu.go
To fix a wrong key name when running a qemu VM with ignition, we need to replace `opt/com.coreos` with `opt/org.flatcar-linux`.
See also https://github.com/flatcar-linux/ignition/issues/2
> platform: fix qemu key name to org/flatcar-linux

- platform/api/packet/api.go
Since upstream changed the config URL to `ignition.config.url`, we should also replace `flatcar.config.url` with `ignition.config.url`.
> platform/api/packet: use ignition.config.url instead of flatcar.config.url

- cmd/plume/README.md
- cmd/plume/containerlinux.go
- kola/tests/docker/docker.go
- kola/tests/misc/grub.go
- kola/tests/misc/update.go
- kola/tests/misc/verity.go
- kola/tests/rkt/rkt.go
This PR consists of most changes to support ARM architecture for Flatcar Linux.
A bunch of changes are about reverting old commits that dropped ARM architecture, back in mid 2018.
Should be merged together with https://github.com/flatcar-linux/bootengine/pull/4 https://github.com/flatcar-linux/coreos-overlay/pull/88 https://github.com/flatcar-linux/scripts/pull/23.
>  Support for ARM architecture

- kola/tests/misc/grub.go
Needed because Jenkins tests against gofmt.
> kola/tests/misc/grub.go: Fix formatting with gofmt

- sdk/enter.go
So far `cork enter` has mounted only `/proc` inside the container, not `/proc/sys/fs/binfmt_misc`.
It caused the cross-build environment not to detect binfmt config changes.
Mount `binfmt_misc` into chroot to fix it.
> sdk: make cork enter mount binfmt_misc

- cmd/plume/containerlinux.go
To allow Jenkins pipelines to publish ARM64 images for AWS, we need to add arm64 to list of boards.
For now it is only for Alpha and Edge, as other channels do not have ARM images yet.
> cmd/plume: publish ARM64 for AWS for Flatcar Alpha and Edge

- platform/qemu.go
Some tests where multiple containers are
spawned in parallel were failing because
of out-out-memory errors.
Slightly increase the memory to allow for
the failing containers to be spawned.
**Note:** Should be cherry-picked for -edge and alpha.
> Increase RAM for QEMU machines

- platform/api/packet/api.go
The kola test times out because the iPXE boot takes too long to get the full installation done in time.
**Note:** Pick for alpha and edge.
> packet: Increase provisioning timeout because of iPXE boot

- platform/api/packet/api.go
The arm64 build is only released for alpha and tested on the `c2.large.arm` instance type.
Note: Start Jenkins mantle build after merging.
> packet: Specify working ARM URL and server type

- platform/platform.go
Sometimes it may take longer, so tolerate these cases.
Also, give more time to check the instance manually
before it is deleted due to a timeout.
> platform: Increase SSH retries to wait up to 10 min

- platform/api/aws/ec2.go
- platform/api/aws/network.go
The subnet determines the Availability Zone. If in that
zone no machines are available, running an instance
will fail. The other Availability Zones probably have
machines available and the code should try to run
instances there instead of giving up too early.
> platform/api/aws: Iterate over all subnets to run the instances

- cmd/ore/aws/upload.go
- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
- cmd/plume/release.go
Currently the AMI names clash for amd64 and arm64 releases.
Therefore, no AMIs for arm64 were created.
Add a "-arm64" tag to the AMI name to distinguish the
arm64 AMI names. This introduces no change to the AMI name
for the existing amd64 AMIs.
> plume: Include -arm64 in AMI name for arm64 images

- sdk/create.go
In some cases, users might want to run `cork create` under a limited environment, where only limited GIDs are available. Github workflows CI is one of the examples, since each CI instance is a Docker container with the latest Ubuntu. In that case, outside of the cork chroot, GID for group `docker` is `115`, while inside of the chroot, GID for group
`docker` is `233`.
So when `cork create` tries to run a script which tries to run `useradd -u UID -g 115` inside the chroot, it fails because of the missing GID 115.
So we should actually make the internal script detect the existing GID 233 to be used for GID of `useradd` command.
> sdk: reuse an existing GID upon cork create in a limited environment

- cmd/ore/aws/upload.go
- cmd/plume/prerelease.go
- cmd/plume/release.go
- platform/api/aws/ami.go
- platform/api/aws/images.go
Removes uploading of the deprecated AWS PV AMIs in `ore` and `plume`.
> ore|plume: Remove PV support

- cmd/plume/containerlinux.go
Even though ap-northeast-3 is specified as default
region, it is not available by default at the moment.
> cmd/plume/containerlinux: Disable ap-northeast-3

- platform/api/aws/images.go
Include the name/ID in the error message.
> platform/api/aws: Make describeImage errors more specific

- platform/qemu.go
Since systemd v243, systemd-journald start crashing with OOM when the test VM runs with RAM of 1280M.
So we need to increase RAM to 2G for amd64 as well, to make it run without OOM.
> platform: increase RAM to 2G for amd64 as well

- sdk/repo/verify.go
Currently only SHA1 git commits can be verified
to be checked out. Add support to verify that
a branch is checked out.
> Verify repo checkout for branch names

- cmd/kola/kola.go
- cmd/kola/options.go
- cmd/kola/spawn.go
- kola/harness.go
- kola/tests/kubernetes/controllerInstall.go
- kola/tests/kubernetes/setup.go
- kola/tests/kubernetes/workerInstall.go
- platform/cluster.go
- platform/conf/conf.go
- platform/flight.go
- platform/platform.go
- kola: Improve debugging abilities through SSH login  
The tests in "kola run" used a temporary SSH key and
directly deleted the machines after a failure.
Add the same SSH key option as in "kola spawn"
to include additional SSH keys (just "-k" is
enough to include the agent/default SSH keys).
Also use the option to skip machine removal as
in "kola spawn --remove=false".
- Use the private IP because the default firewall
rules do not allow incoming traffic on 2379 for
the public IP.
Also, there are no FLATCAR_*_IP* variables set up in
/etc/environment for machines running in
Google Compute Engine because (as with afterburn)
the prefix is still COREOS_.
> kola: Improve debugging abilities through SSH login

- kola/tests/misc/network.go
The test cl.network.listeners checks for active listener sockets.
It uses `netstat -plutn` to list listeners which may truncate the
program name. Since the output is compared to predefined strings
the test may fail if the combination of PID, "/", and program
name exceeds 19 characters.
This change truncates the expected string to the constraints lined
out above, which fixes the test.
To reproduce the error, run this test e.g. on Azure, where it
reproducibly fails because the PID of systemd-networkd has
4 digits:
```
bin/kola run cl.network.listeners --platform azure --azure-disk-uri <flatcar-image-URI> --azure-location <location-of-image>
```
For testing, the following URI / location may be used (transient, images will be removed eventually):
```
Image URI: …
```
> kola network.go: fix cl.network.listeners proc truncate

- platform/cluster.go
When a Flight was created not being part of
"kola run" the pointer to additional SSH keys
can be nil.
Check against nil before dereferencing it.
> Fix nil pointer deref for additional SSH keys

- kola/tests/docker/torcx_docker_flag.go
Since the docker 1.12 profile was removed in Edge, many kola tests started to fail to run, because of the missing docker 1.12 profile. Ideally we should be able to make a different set of profiles for each channel. Unfortunately the current Jenkins pipeline is not able to do that. It takes into account only flatcar-master branch.
To work around the issue, read directly a version from `/etc/os-release` to detect if the image is Edge. If the semver's minor version is 99, then it means Edge, so skip the tests.
Note, the code is only a quick-and-dirty approach. In the future, we should create a generic way to make channel names available for individual tests.
> kola: skip Docker torcx tests in case of Edge channel

- cmd/kola/kola.go
- cmd/kola/options.go
- cmd/ore/azure/upload-blob-arm.go
- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
- cmd/plume/release.go
- cmd/plume/types.go
- platform/api/azure/api.go
- platform/api/azure/image.go
- platform/api/azure/options.go
- platform/api/azure/storage_mit.go
- platform/machine/azure/flight.go
This uses the v2 API for plume because the classic OS images
are not working with kola and we also migrated the storage
account.
The prerelease step is also simplified because the
image is not necessary for the followed release step as it
directly works with page blobs.
For kola tests we better create an image where needed.
The "pre-publish" container is not used anymore.
Instead of "sharing" the image we now create a SAS URL
which we need to specify in the SKU. This step remains
manual for now.
In addition, there are new command line flags for testing plume.
For kola the options --azure-image-file and --azure-blob-url
were added to directly upload a file into the temporary resource
group or to copy a blob from another storage location into the
temporary resource group (the blob may be …
> Port plume/kola to v2/ARM for Azure and remove outdated steps

- platform/api/azure/storage_mit.go
According to the SAS URL requirements in
https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal/virtual-machine/cpp-get-sas-uri#verify-the-sas-uri
and
https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal/virtual-machine/cpp-common-sas-url-issues
we should grant List permissions.
Maybe this is still not enough and we need to update
to a newer API to get the correct start/
expiry time formats.
> Azure: Add list permissions to SAS URL

- cmd/ore/aws/upload.go
- cmd/plume/prerelease.go
- platform/api/aws/images.go
- platform/api/azure/storage_mit.go
If images with the same name existed, they were reused by plume.
This meant that a fix for a release would not be uploaded because
it had the same image name.
Add a flag to force image uploading by removing any existing AMIs/
snapshots with the same name.
> plume pre-release: Add flag to force image upload

- platform/api/azure/instance.go
Wrap the error in an error message unique for this line
to help debugging.
> platform/api/azure: Give context for error

- cmd/kola/kola.go
- kola/harness.go
- kola list: Platform/distro filters with glob patterns
The "kola run" command accepts a glob pattern to limit which tests are run.
To test a pattern before running a test, add a filter option to
"kola list" to filter the list of known tests by platform and distro,
and if wanted with a glob pattern to see its effect.
- kola run: Accept a list of glob patterns  
Glob patterns are matching like the shell expands a glob pattern.
This does not allow to test against two names that don't share a
substring. On the shell this is solved by having two glob arguments.
Allow multiple glob patterns to be specified as arguments to handle
the cases where the tests don't share a substring but we want to run
exactly those tests.
> kola run: Accept a list of glob patterns, kola list: Platform/distro filters with glob patterns

- kola/tests/ignition/passwd.go
For ignition to successfully change password hashes, the unit `system-cloudinit@user-share-flatcar-developer_data.service` must be masked.
Otherwise, the unit will run again cloudinit, which will change the user password again, and the ignition tests will fail like this:
```
--- FAIL: cl.ignition.v1.users (19.77s)
passwd.go:321: "core" wasn't correctly created:
got "core":"$1$q5c1evy8$i6MbDRMPJeY28scalaUrM/", expected "core":"foobar"
```
We need to fix unit names, from `coreos` to `flatcar`, so that the correct unit can be masked.
> kola: fix unit names for system-cloudinit service

- kola/tests/misc/network.go
This change adds `systemd-timesyncd` to the list of expected listener processes in the test `cl.network.listeners`. 
`systemd-timesyncd` is an NTP client service which will not listen constantly but only run occasionally, binding to random UDP client ports when running. Therefore, the test does not check for a port number.
- check out: `gh pr checkout 76`
- build: `make -j`
- run qemu test (needs a Flatcar qemu image: `sudo ./kola run cl.network.listeners --debug --platform qemu --qemu-bios=bios-256k.bin --qemu-image flatcar_production_qemu_image.img`
- Ran the above commands and validated the change does not break `cl.network.listeners`
- Did not explicitly validate against a running `systemd-timesyncd` as the NTP client only runs occasionally, for a short period of time. We've seen the …
> cl.network.listeners: add systemd-timesyncd

- cmd/ore/aws/upload.go
- cmd/plume/prerelease.go
- cmd/plume/release.go
- platform/api/aws/images.go
- plume/ore: Derive AWS AMI architecture from board
Only x86_64 was always used as architecture for AWS AMIs.
Set the correct AMI architecture depending on the board.
- plume: Remove duplicate architecture tag from AWS image name
The architecture tag was first added to the image before the -hvm suffix
and then later added to the image metadata.
Since the metadata is used for the image name, we ended up with
adding the architecture tag twice for the pending release:
Flatcar-edge-2466.99.0-arm64-arm64-hvm
Do not append the architecture tag before the -hvm suffix.
Used in Jenkins `os/(pre)release`.
None
> Fix AWS AMI architecture and name

- platform/api/packet/api.go
When the DNS resolving failed, the installer failed directly, too.
Add retry options to curl so that it gets more robust against
temporary network issues (external or internal).
`kola spawn --platform packet`
None
> Packet: Make curl more robust when installing via iPXE

- kola/tests/docker/docker.go
Since runc 1.0-rc7 or newer, memory consumption of runc has increased, so Docker has not been able to run containers with cgroup memory limit > 10MB.
The memory consumption issues were improved since 1.0-rc8, but not completely. 
That's why some docker tests have failed with the following messages.
```
--- FAIL: docker.base/resources (34.69s)
cluster.go:117: /run/torcx/bin/docker: Error response from daemon: cannot start a stopped process: unknown.
docker.go:302: [0] failed to run "docker run --rm --memory=20m --memory-swap=20m sleep sleep 0.2": output: "" status: "Process exited with status 125"
```
We need to increase the limit from to 30MB, to make the tests work again.
On an AWS instance (m5.large, 8GB mem):
```
tmpdir=$(mktemp -d); cd $tmpdir; echo -e "FROM scratch\nCOPY . /" > …
```
> kola: increase cgroup memory limit to 30MB

- kola/tests/docker/docker.go
With 30MB, docker run still fails in some cases.
Let's increase the cgroup memory limit to 50MB, to avoid such failures.
Other details are already described in https://github.com/flatcar-linux/mantle/pull/79.
> kola: increase cgroup memory limit to 50MB

- cmd/kola/kola.go
- cmd/kola/options.go
- kola/harness.go
- kola/register/register.go
Add argument to enable channel based testing
This PR adds the argument `--channel` to enable channel based testing, which
means you can populate the Channel property in kola tests and kola would decide to
include/exclude the test based on which channel it is running.
This PR also output the channels when the list subcommand is run both with or without `--json`
`./bin/kola run [--channel <channel>]`
`./bin/kola list [--channel <channel>]`
Both the outputs are snipped.
```
$ ./bin/kola list
Test Name                                       Platforms       Architectures   Distributions   Channels
cl.basic                                        [all]                                                   [all]   [cl]            [all]
cl.cloudinit.basic                              [aws azure do esx …
```
> kola: Add argument to enable channel based testing

- kola/tests/kubernetes/basic.go
The test `google.kubernetes.basic.docker.v1.3.4_coreos.0` is not compatible
with Docker 19.06.
See https://github.com/flatcar-linux/Flatcar/issues/79#issuecomment-613619548
for details.
The following output is empty as wanted:
```
./kola list --filter --platform gce --channel edge | grep google.kubernetes.basic.docker.v1.3.4_coreos.0
```
> Skip old Kubernetes test for Alpha/Edge channels

- cmd/kola/options.go
- platform/machine/packet/cluster.go
The retry loop relies on having access to the last error. This error value
was shadowed in some cases which caused the error not be be logged and the
function to report a nil error when the maximal number of retries was reached.
Never shadow the error variable with local error variables in for/if scopes so
that the error value is assigned to the functions error variable.
Run kola tests for arm64 on Packet.
```
./kola spawn -d -k --board=arm64-usr --gce-json-key gce-token.json --packet-facility=sjc1 --packet-project=ABC --packet-storage-url=gs://flatcar-jenkins/mantle/packet --platform=packet --packet-api-key=XXX --packet-installer-image-base-url http://8.8.8.8/404
```
Provisioning should fail 3 times and kola spawn should end with an error.
A faster way to fail provision early is …
> Packet: Always report error when provisioning failed

- cmd/kola/options.go
Kola currently uses an instance size with 1GB RAM on DigitalOcean. This leads to docker tests from the `docker.base` suite to fail from resource exhaustion (OOM kills).
This change makes `kola` use DO's `s-1vcpu-2gb` instance size by default.
```
./ore do create-image --config-file ~/.do/token.json --name=kola-test-2gb --url=https://storage.googleapis.com/flatcar-jenkins/edge/boards/amd64-usr/2466.99.0/flatcar_production_digitalocean_image.bin.bz2
./kola run --basename=kola-test-2gb --do-config-file ~/.do/token.json --do-image=kola-test-2gb --platform=do docker.base
./ore do delete-image --name=kola-test-2gb --config-file ~/.do/token.json
```
Ran the above commands, tests passed.
> kola: default to 2GB instance size on digitalocean

- cmd/plume/containerlinux.go
- cmd/plume/plume.go
Make AWS partition selectable via cmd flag
```sh
plume pre-release --partition=default
```
I haven't run any tests yet.
> plume: select aws partition by flag

- kola/tests/docker/torcx_docker_flag.go
#61 implements a hacky way to exclude the Docker torcx tests for the edge channel. Now that we have a proper way, I've reverted the change and added the necessary changes.
./kola run --channel edge
./kola run --channel alpha
I've just built the code to see if it builds
> kola: Exclude Docker torcx tests for Edge Channel

- kola/tests/kubernetes/basic.go
- kola/tests/kubernetes/controllerInstall.go
- kola/tests/kubernetes/setup.go
- kola/tests/kubernetes/workerInstall.go
Starting from Docker 19.03, we need a newer version of Kubernetes or our deployment doesn't work. So we switch to testing newer k8s versions.
This includes updating quite a few Kubernetes flags that were deprecated since the old version we were using, to use the new names and formats (some flags were renamed, others had to be moved to config files, others don't exist anymore). Supporting different Kubernetes versions also means adding some conditional behavior for commands that changed along the way.
This commit also switches to the hyperkube images provided by gcr.io instead of the ones provided by quay.io, as those were discontinued. To get this to work we need to prepend the ACI with docker:// and set the --insecure-options=image option (See coreos/coreos-kubernetes#583)
It also …
> Switch to Hyperkube v1.14+.

- cmd/plume/prerelease.go
In case that `gceJSONKeyFile` is not set, don't upalod AMI list
> plume: flag out upload for unauth calls

- cmd/kola/options.go
- platform/api/esx/api.go
Cloning from a base VM to spare the image upload is not supported by
the free version of ESXi. It is also useful for "kola spawn" to work
without a base VM.
Add an option to create a VM directly from an uploaded image.
The userdata is set over guestinfo variables instead of modifying the
default values of the OVF metadata.
Create a VM on a [Packet.net ESXi server](https://www.packet.com/resources/guides/esxi/):
```
./kola spawn --platform esx --esx-config-file esx.json --esx-ova-path flatcar_production_vmware_ova.ova  -d
```
By default this give an error because the VM expects DHCP to be set up which isn't the case in the default Packet.net ESXi configuration. To work around this I used a custom userdata in kola to set a password and log in to the VM over the VGA console through the web …
> ESX: Add kola option to work without a base VM

- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
In order to enable developer builds we need to have a fully working developer channel. This adds support the necessary support to plume.
On AWS this channel will upload the image to only one region.
This change also re-organizes the default values for the Azure and AWS specifications, to avoid excessive copying and pasting when adding a new channel.
Needed for: kinvolk/PROJECT-flatcar-linux#294
I've tested this for both AWS and Azure with the following command lines:
```
bin/plume pre-release --debug --platform=aws \
--aws-credentials=/home/marga/kinvolk/.creds/aws-release-credentials \
--gce-json-key=/home/marga/kinvolk/.creds/gce-service-account.json \
--board=arm64-usr --channel=developer --version=2466.0.0 \
--write-image-list=images.json …
```
> cmd/plume: Add a developer channel

- cmd/ore/esx/esx.go
The default ESX config path was always used.
Add the same flag that kola also has to provide a different path.
```
./ore esx remove-base --name kola-54ab7aa4… --esx-config-file esx.json
```
Before:
```
./ore esx remove-base
could not create ESX client: couldn't read ESX config: open /home/…/.config/esx.json: no such file or directory
```
After:
```
./ore esx remove-base --esx-config-file /dev/null
could not create ESX client: couldn't read ESX config: EOF
```
> ore: Add option for ESX config path

- cmd/plume/containerlinux.go
The verification script in os/prerelease looks at the us-west-2 region, so put developer builds in that region instead of Europe.
For this to work, a new S3 bucket had to be created.  I've created `flatcar-developer-ami-import-us-west-2` in us-west-2 and gave it the same permissions and policies as the other bucket.
Tested this change with: `bin/plume pre-release --debug --platform=aws --aws-credentials=/home/marga/kinvolk/.creds/aws-release-credentials --gce-json-key=/home/marga/kinvolk/.creds/gce-service-account.json --board=amd64-usr --channel=developer --version=2345.3.1+jenkins2-flatcar-master-382 --write-image-list=images.json --verify-key=/home/marga/kinvolk/.creds/verify.asc`
> cmd/plume: Move developer builds to us-west-2

- cmd/kola/options.go
- kola/tests/ignition/resource.go
- kola/tests/ignition/security.go
- platform/api/esx/api.go
- platform/conf/conf.go
- platform/machine/esx/cluster.go
- platform/machine/esx/flight.go
- platform/machine/esx/machine.go
- esx: Allow to configure static IPs    
The default ESXi setup does not have a DHCP server but expects
static IPs to be used (e.g., see https://www.packet.com/resources/guides/esxi/).
Allocate static IPs for each machine from a number of addresses
starting with a specific address given inside the subnet (in Packet this
is the next IP address after the host's IP, see link above).
A networkd configuration file is used with Ignition but cloud-config writes its
own networkd configuration file based on the guestinfo.interface* variables.
The coreos-metadata service uses the COREOS_CUSTOM_* variables that are known
to the Container Linux Config Transpiler, too, and got some robustness fixes.
```
./kola run -d --platform esx --esx-config-file esx.json --esx-ova-path …
```
> esx: Allow to configure static IPs

- go.mod
- go.sum
The golang Docker containers do not include bzr which caused the
build to fail for the gocheck library.
Switch to the GitHub repository which is the new upstream location.
> Use new location for gocheck that works with git and not bzr

- auth/esx.go
- platform/api/esx/api.go
- platform/machine/esx/cluster.go
- esx: Optionally read static IP config from ESX profile
Instead of a long list of command line options, the static IP configuration
should be part of the config file.
The values can be left out and the command line options get preference.
- esx: Always remove created VM on error
- esx: Free static IP up when device creation failed
> esx: Optionally read static IP config from ESX profile

- cmd/ore/esx/list-vms.go
- cmd/ore/esx/remove-vms.go
- platform/api/esx/api.go
The list command for `ore` allows to see if any VMs exist on ESXi. The remove command allows to delete these VMs. Both commands take a pattern to match for (similar to shell globs).
```
./ore esx --esx-config-file esx.json list-vms
kola-0df55961-a4e2-42f0-99ec-39eb21091864-117b901c07
./ore esx --esx-config-file esx.json remove-vms --pattern 'kola-*'
kola-0df55961-a4e2-42f0-99ec-39eb21091864-117b901c07
```
> esx: Add ore commands to list and remove VMs by pattern

- kola/tests/docker/torcx_manifest_pkgs.go
Our tests use a static IP which is set up after Ignition or
coreos-cloudinit ran but torcx needs it to be set up during the
initramfs already.
> kola: Skip docker.torcx-manifest-pkgs on VMware ESXi

- platform/api/esx/api.go
The tests docker.lib-coreos-dockerd-compat and docker.base fail
because the VM has only 1 GiB of RAM.
Set the VM RAM to 2 GiB.
Tested on ESXi (make sure you are the only one creating a VM there or set `--esx-first-static-ip` and `--esx-first-static-ip-private` to be higher and reduce `--esx-static-ips`):
```
$ wget https://alpha.release.flatcar-linux.net/amd64-usr/2492.0.0/flatcar_production_vmware_ova.ova
$ ./kola run -d --platform esx --esx-config-file esx.json --esx-ova-path flatcar_production_vmware_ova.ova docker.lib-coreos-dockerd-compat docker.base
```
> esx: Use 2 GiB RAM on VMware VMs to pass the docker tests

- kola/tests/docker/docker.go
Extend the Docker option test with two --security-opt cases where
one currently broke in Alpha 2492.0.0. See
https://github.com/flatcar-linux/Flatcar/issues/110
```
$ make
$ cd bin
$ wget https://alpha.release.flatcar-linux.net/amd64-usr/2492.0.0/flatcar_production_qemu_image.img.bz2
$ (l)bunzip2 flatcar_production_qemu_image.img.bz2
$ sudo ./kola run --qemu-image flatcar_production_qemu_image.img --qemu-skip-mangle docker.base
```
Result for Alpha as above (`WARNING` can be ignored):
```
=== RUN   docker.base
=== RUN   docker.base/docker-info
=== RUN   docker.base/resources
=== RUN   docker.base/networks-reliably
=== RUN   docker.base/user-no-caps
--- FAIL: docker.base (221.02s)
--- PASS: docker.base/docker-info (0.57s)
--- FAIL: docker.base/resources (49.74s)
cluster.go:117: WARNING: …
```
> kola/tests/docker: Test no-new-privileges security option

- sdk/repo/verify.go
The branch name was falsely assumed to contain no slashes.
Keep all slashes after the one that separates the origin.
Also filter away local tags which would break the rule that
all after the first slash is a branch name.
> sdk/repo/verify: Keep slashes in branch names

- cmd/cork/create.go
- cmd/cork/download.go
- sdk/download.go
The SDK path for the Google Cloud Storage URL was hardcoded to
point to the directory of SDK releases.
Add a parameter to allow to download a developer SDK build
(currently in /flatcar-jenkins/developer/sdk).
```
$ mantle/bin/cork create --sdk-url-path '/flatcar-jenkins/developer/sdk' --sdk-version '2492.0.0+dev-flatcar-build-2492.0.0-local-418'
```
> cork: Add SDK URL path parameter

- kola/tests/docker/docker.go
Recently two Docker parameter test cases were added:
1. --security-opt=label=disable --security-opt=no-new-privileges
2. --security-opt=no-new-privileges
As the second case causes a Docker 1.12 runc panic in our current
setup, skip this test when Docker 1.12 is detected.
```
$ make
$ make test
$ cd bin
$ ./kola run --board=amd64-usr --aws-ami=ami-0c7295725fccdee9b --aws-region=us-west-2 --aws-type=t3.small --aws-iam-profile=jenkins-test --platform=aws --channel=beta --torcx-manifest=torcx_manifest.json --aws-credentials-file ~/.aws/credentials-kola docker.torcx-manifest-pkgs
```
with this content for the file `torcx_manifest.json`:
```
{  "kind": "torcx-package-list-v0",  "value": {    "packages": [      {        "name": "docker",        "versions": [          {            "version": …
```
> kola/tests/docker: Skip no-new-privileges test for Docker 1.12

- kola/tests/kubernetes/controllerInstall.go
- kola/tests/kubernetes/workerInstall.go
Ref: https://github.com/flatcar-linux/Flatcar/issues/121
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
I don't want `--insecure-options=` to live on here, but rather test the places that rkt fetches from quay.io
run the kola tests
Not done yet. I'm still learning this area.
> kola: force rkt to use docker API for quay

- cmd/gangue/gangue.go
- cmd/gangue/get.go
- cmd/gangue/prune.go
- go.mod
- go.sum
By adding developer builds, we've started generating a lot of files in GCS that are actually ephemeral. This change adds a new `prune` subcommand to the gangue command (until now only `get` existed). This subcommand can be used to delete files under a specific path if they are older that some amount of days.
```
go build -o bin/gangue github.com/coreos/mantle/cmd/gangue
bin/gangue prune flatcar-jenkins developer/sdk \
--json-key /path/to/creds/gce-service-account.json --days=15
```
This will delete all files older than 15 days under the `developer/sdk` path.  I've run this for sdk and for boards and verified that the files deleted were correct.
This change is part of the clean up needed for building PR branches (kinvolk/PROJECT-flatcar-linux#294)
> Add a gangue subcommand to clean up files in GCS

- kola/tests/locksmith/locksmith.go
On VMware ESXi there were reproduceable test failures with kola due to
the certificate date ("certificate is not yet valid") but these
failures were not reproducible by executing the same commands manually.
Cover the failing command in a rety loop because I suspect that the
system time got slightly adjusted or something similar in between
which causes the certificate to be invalid for a short time.
```
./cork download-image --cache-dir=tmp --json-key=/dev/null --platform=esx --root=gs://flatcar-jenkins/beta/boards/amd64-usr/2513.2.1
./ore esx --esx-config-file esx.json remove-vms
./kola run -d --esx-config-file esx.json --esx-ova-path tmp/flatcar_production_vmware_ova.ova --parallel=4 --platform=esx --channel=beta --tapfile=vmware-esx.tap coreos.locksmith.tls
```
> kola/tests/locksmith/locksmith: Make coreos.locksmith.tls more robust

- kola/tests/kubernetes/kubelet_wrapper.go
Encountering quay.io timeouts, the service failed and was detected
as failed service in the instance check of the
kubernetes.kubelet_wrapper.var-log-mount test.
Add a retry option to the kubelet service in case the errors can be
resolved quickly by running rkt again.
```
/kola run -k -d --parallel=1 --basename=your-test --board=amd64-usr --channel=alpha --platform=azure '--azure-blob-url=https://flatcar.blob.core.windows.net/publish/flatcar-linux-2513.0.1-alpha.vhd?se=2099-12-31T23%3A59%3A59Z&sig=2T45Z2uti5b8lc%2BSC3NeeFd1NooUFlRcuGSy75Tokxc%3D&sp=rl&sr=b&sv=2015-02-21' --azure-location=northeurope --azure-profile ~/.azure/profile.json --azure-auth ~/.azure/credentials.json --tapfile=azure.tap kubernetes.kubelet_wrapper.var-log-mount
```
Ongoing…
> kola/tests/kubernetes/kubelet_wrapper: Restart kubelet service

- platform/api/azure/instance.go
The regex patterns to process the URL were assuming that the test names would all start with "kola-", which is not true when running Jenkins tests. This caused the container and blobName variables to be empty, making it impossible to get the console output.
On top of this, the function that reads the data was always returning an error, which meant that the data was never written, even if it could be obtained successfully.
This change fixes the regex patterns, adds a lot more error handling, and returns non-error when the function succeeds
`bin/kola run --parallel=1 --basename=marga-test --board=amd64-usr --channel=beta --platform=azure '--azure-blob-url=https://flatcar.blob.core.windows.net/publish/flatcar-linux-2512.1.1-beta.vhd?se=2099-12-31T23%3A59%3A59Z&sig=FAiqfI5MVw7b11kNc%2Bfb7OMQjp …
> Azure platform: fix getting the console output

- platform/api/azure/instance.go
- platform/machine/azure/cluster.go
- platform/machine/azure/flight.go
- platform/machine/azure/machine.go
Each kola cluster created and destroyed its own Resource Group which
took 2-3 minutes.
Reuse the image Resource Group if it was created for the flight and
run all tests in it. To keep the amount of left over VM network objects
small, the IP addresses and NICs are deleted when an instance is
deleted - this could also be removed again if we see that deleting
these objects takes a lot of time.
```
./kola run -d --parallel 1 -k --platform azure --azure-blob-url 'https://flatcar.blob.core.windows.net/publish/flatcar-linux-2513.1.0-alpha.vhd?se=2099-12-31T23%3A59%3A59Z&sig=q93Hf6UggelIS3VQ%2F9sIjoz0CeREpX93o9tgTnRBrqk%3D&sp=rl&sr=b&sv=2015-02-21' --azure-location YOURLOCATION --azure-profile azureProfile.json --azure-auth service-credentials.json
```
> azure: use one Resource Group for all tests

- cmd/plume/prune.go
- platform/api/aws/images.go
- platform/api/aws/s3.go
- platform/api/azure/storage_mit.go
When running developer builds, plume uploads prerelease images to both Azure and AWS. This change adds a new "prune" subcommand for plume, to get rid of artifacts uploaded to old builds.
It also adds or improves logging messages on functions. This extra logging was needed for debugging while developing the code.
```
go1.14.4 build -o bin/plume github.com/coreos/mantle/cmd/plume
./bin/plume prune --channel developer --version none --azure-auth ../../.creds/azureCredentials.json --azure-profile ../../.creds/azureProfile.json --aws-credentials ../../.creds/aws-release-credentials --days 20 --debug
```
I've already run this for Azure and AWS with days=20, so to test it, it needs to be run with a smaller number or it won't do anything.
Needed for: kinvolk/PROJECT-flatcar-linux#294
> cmd/plume: Add a prune command to clean up developer images

- cmd/plume/prerelease.go
The functions `createAzureImage` and `replicateAzureImage` are not currently used by any code. Having them around just creates confusion when trying to understand what prerelease does.
> cmd/plume/prerelease: Delete unused functions

- cmd/ore/gcloud/create-image.go
To make it easier to find the latest stable/beta/alpha image, we need to set the image family when adding images to gcloud.  This won't be relevant for images uploaded for Kola tests, but will be relevant for images uploaded to the public project
```
bin/ore gcloud create-image --board=amd64-usr --family=flatcar-edge --source-root=gs://flatcar-jenkins/edge/boards --version=2466.99.0 --json-key /path/to/key.json
```
Then verify that the created image has a family field.
I've added the new images in the kinvolk-public project by running the above command (once per channel, for the corresponding version of each channel) and each image now has the right associated family.
> ore/gcloud: Add Image Family when creating image

- cmd/cork/create.go
- sdk/version.go
The SDK version parameter for "cork create" and "cork update" was used
to download a specific SDK tar ball but the SDK version entry in
version.txt stayed on the original value of the manifest. This caused
"cork update" or a later update_chroot step to not find the right
binary packages.
Set the correct SDK version value in the version.txt file.
```
mantle/bin/cork update --create --sdk-version VERSION
```
```
mantle/bin/cork update --create --sdk-version 2345.3.1
cat .repo/manifests/version.txt # verified the SDK version entry
cat chroot/etc/portage/make.conf # verified that update_chroot picked it up to download binary packages
```
> cork: Set SDK version in the manifest version.txt

- kola/tests/misc/users.go
After the systemd 245 update `getent passwd` also reports an entry for
root with a /bin/sh login shell. Since /bin/sh is a symlink to
/bin/bash this is acceptable even though I didn't find out yet what
caused this change.
```
wget https://storage.googleapis.com/flatcar-jenkins/developer/developer/boards/amd64-usr/2020.07.29+dev-flatcar-master-678/flatcar_production_qemu_image.img.bz2
lbunzip2 flatcar_production_qemu_image.img.bz2
sudo ./kola run --board=amd64-usr --channel=alpha --parallel=1 --platform=qemu --qemu-bios=bios-256k.bin --qemu-image flatcar_production_qemu_image.img cl.users.shells
rm flatcar_production_qemu_image.img
```
> kola/test/misc/users: Cover case of dereferenced login shell symlink

- kola/tests/misc/nfs.go
- kola/tests/misc/ntp.go
- kola/tests/systemd/journald.go
- platform/local/dnsmasq.go
- platform/machine/qemu/cluster.go
- platform/machine/unprivqemu/cluster.go
- platform/machine/qemu: Log IP address in debug mode
- platform/machine/unprivqemu: Log localhost port for SSH connections
- Log PIDs of qemu machine processes for manual cleanup
- kola: Remove unnecessary deletion of test machines
The cluster deletes all machines if needed. Deleting them inside the
tests broke the --remove=false flag to keep machines for debugging.
```
sudo ./kola run -d --remove=false --key ~/.ssh/id_rsa.pub -k --board=amd64-usr --channel=alpha --parallel=1 --platform=qemu --qemu-bios=bios-256k.bin --qemu-image flatcar_production_qemu_image.img systemd.journal.remote 2> >(tee pidlog >&2)
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="sudo nsenter -n -t $(grep 'dnsmasq.*manual cleanup needed' pidlog | cut -d : -f 5) nc %h %p" -p 22 …
```
> Improve QEMU debugging

- test
The CI does not have bzr installed and fails to fetch a module which
still uses this location.
Build on a host system without `bzr`
None, maybe `replace launchpad.net/gocheck => gopkg.in/check.v1 v1.0.0-20200902074654-038fdea0a05b` is also needed
> Set mod=vendor when building with go install

- go.mod
- go.sum
The go-check repository on launchpad could only be reached with
bzr installed.
Replace the launchpad reference by a newer version on gopkg.in.
> Replace go-check bzr location with a git location

- platform/qemu.go
Using only a single core for the VMs limits the test execution speed.
Allocate 4 virtual CPUs which should be a good default.
```
sudo ./kola run -d -k --qemu-image flatcar_production_qemu_image.img cl.basic
```
I entered the virtual machine as follows and checked the output of `lscpu`.
```
ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="sudo nsenter -n -t $(ps -ef | grep '^dnsmasq.*dnsmasq --conf-file=-' | tail -n 1 | awk '{print $2}') nc %h %p" -p 22 core@10.0.0.2
```
> platform/qemu: Use 4 virtual CPUs instead of 1

- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
- cmd/plume/types.go
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
This change introduced a new AzurePremium spec for all the channels and adds logic to handle the image file to upload it to Azure.
> Add the support for Azure Premium images

- cmd/plume/containerlinux.go
- cmd/plume/types.go
> plume: Add a private flag to spec to maintain a private bucket

- cmd/plume/prerelease.go
While doing the sanity check, don't check if the bucket is private.
> Don't check for the version file if the bucket is a private one

- cmd/kola/options.go
- cmd/plume/containerlinux.go
- cmd/plume/release.go
This makes kola accept the `lts` channel parameter for test filtering and also registers the LTS channel to plume for Azure/AWS but doesn't make AMIs public.
Use with Jenkins
None
> Add LTS channel to plume and kola

- kola/harness.go
- platform/local/flight.go
- platform/machine/qemu/flight.go
- platform/qemu.go
I've been chasing an error that has turned up in our Jenkins workers in the past few days where sometimes QEMU would fail the mount operation for the OEM partition of the loop device.  To understand the problem better, I've added a bunch of additional error messages here and there.
Eventually, I found that the problem was caused by the loop devices getting created twice, with a brief pause in between where they didn't exist.  This turns up in dmesg like this:
```
[399319.680160]  loop1: p1 p2 p3 p4 p6 p7 p9
[399319.705589]  loop1: p1 p2 p3 p4 p6 p7 p9
```
With some additional debugging info (not included in this PR), I could see this:
```
2020-09-24T13:06:46Z platform: oemdev file stat: &{loop1p6 0 67109248 {447130408 63736549606 0x388a680} {5 85487090 1 24960 0 0 0 66309 0 4096 0 …
```
> Retry mounting the loop device in QEMU and improve error messages

- kola/tests/coretest/core.go
When a symlink is relative and not absolute and it's having a ./ prefix
the test was reporting an error because it expected to get the plain
filename of a relative path.
Trim any ./ prefix to relax the constraints.
Run `cl.basic` tests with the unreleased image.
None
> kola: Resolve relative paths to the same directory

- platform/machine/packet/cluster.go
The console log file could have been deleted when destroying the
unsuccessful machine, thus don't error out when the file can't be
deleted again. Also don't hide the previous error behind the INFO log
level which is not the default.
Run kola tests on Packet.
None
> platform/machine/packet: No need for prev console log to exist to retry

- platform/api/packet/api.go
Without any OEM information the default DHCP setup for one of the
interfaces works ok and is required to work inside the initramfs
but later after the initramfs the network setup provided by the
metadata server should be used. This is what is currently used in the
real PXE installation processes and should be covered by our CI. It is
also needed as soon as there is a change that assumes the network setup
according to the metadata server is done after the initramfs.
Run kola tests
None
> Packet: Set OEM ID for PXE boot network setup

- platform/qemu.go
As the flatcar_production_qemu*.sh scripts already do, use the fast
/dev/urandom device from the host as HW random source inside the guest.
```
sudo ./kola run -d --platform qemu --qemu-image flatcar_production_image.bin cl.basic
sudo ./kola run -d --platform qemu --board arm64-usr --qemu-bios flatcar_production_qemu_uefi_efi_code.fd --qemu-image flatcar_production_image.bin cl.basic
```
> platform/qemu: Back HW random device with /dev/urandom

- kola/tests/ignition/resource.go
Since the original S3 bucket `kola-fixtures` was renamed to `rh-kola-fixtures`, we are not able to use the bucket any more.
So we have set up a Flatcar-specific bucket for kola tests. `kola-fixtures` in the `eu-central-1` region.
Those can be accessed via
https://kola-fixtures.s3.eu-central-1.amazonaws.com/resources/...
TBD
> kola: fix S3 URLs for ignition tests

- cmd/kola/options.go
- cmd/ore/packet/create-device.go
- platform/api/packet/api.go
If appending the default file names to the base URL is not resulting in
the correct URL for the kernel and cpio files, there was no way to
specify the correct URLs for both explicitly.
Add two new options that default to the previous behavior if not used.
```
bin/ore packet --api-key X --project X --storage-url X --gs-json-key X create-device --installer-image-kernel-url X --installer-image-cpio-url X --userdata-file X --hostname X
```
> packet: Allow to set explicit URLs for the kernel and cpio files

- cmd/plume/containerlinux.go
- cmd/plume/release.go
This change adds a new `--gce-release-key` parameter to the plume release subcommand, that allows uploading GCE images to the corresponding project.
It also sets all the GCE parameters for the channel spec as needed, and gets rid of some old obsolete CoreOS code.
I also did a small refactor of the containerlinux.go file, extracting the channel descriptions that were repeated in the two Azure offers, as I also needed to use the channel description for the GCE image.
`bin/plume release --debug --board amd64-usr --channel <CHANNEL> --version <VERSION> --gce-json-key gce-service-account.json --gce-release-key gce-image-uploader.json`
Sample run: 
```
$ bin/plume release --debug --board amd64-usr --channel alpha --version 2697.0.0 --gce-json-key gce-service-account.json --gce-release-key …
```
> cmd/plume: enable releasing GCE images

- cmd/ore/gcloud/create-image.go
- cmd/ore/gcloud/upload.go
- cmd/plume/release.go
- platform/api/gcloud/image.go
This change is based on coreos/coreos-assembler@f5d422d (PR: coreos/coreos-assembler#1610)
It adds support for marking images with public ACLs when they are created, and uses this functionality from ore upload, ore create-image and plume release. In the ore subcommands, this is gated with a --public flag, in the plume subcommand, the image is always made public.
Build ore and plume with this change. Run `ore gcloud create-image --public` or `plume release`. Verify that the image was set to public.
This requires the service account to have access to `compute.images.getIamPolicy` and `compute.images.setIamPolicy`.
Tested uploading with ore:
```
./bin/ore gcloud create-image --project kinvolk-public --board amd64-usr --family flatcar-alpha --license flatcar-container-linux --source-root …
```
> Add ability to make GCE images public, use it in ore and plume

- cmd/cork/create.go
- sdk/repo.go
Introduce a new option `--repo-branch` to `cork create` and `update`.
The option allows users to specify an arbitrary branch name passed to the `repo init` command.
Also set the default branch name of repo to `maint`, until the upstream repo >= v2.10 could be available in ordinary SDK environments.
That is to avoid incompatibility issue of an old repo tool not being able to work with the default [`stable`](https://gerrit.googlesource.com/git-repo/+/refs/heads/stable) branch of the repo tool, which does not support python2 any more.
On the other hand, its [`maint`](https://gerrit.googlesource.com/git-repo/+/refs/heads/maint) branch still supports python2.
In the long term, we should update `dev-vcs/repo` in Flatcar SDK to v2.10 with python3, and set the default branch back to `stable`.
``` …
```
> cmd/cork,sdk: introduce --repo-branch option to cork

- kola/tests/misc/network.go
The containerd cri plugin used a TCP port in the past and for Edge it
was allowed to be opened.
Remove this rule because containerd should not listen on TCP anymore
(and for the Alpha, Beta, Stable channels never did).
> kola/tests/misc/network.go: Disallow the CRI plugin to listen on TCP

- cmd/cork/downloadimage.go
- cmd/ore/aws/delete.go
- cmd/ore/aws/upload.go
- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
- cmd/plume/prune.go
- platform/api/aws/images.go
- cmd/plume: Disable AMI creation for the LTS channel
The AMIs were not published anyway and just used for testing.
- cmd/cork: Support downloading AWS Pro images
The AWS Pro images are a different OEM type with a _pro suffix.
- cmd/ore: Delete existing snapshot when --force is used
A mismatched snapshot name resulted in "ore aws upload --force" not
really reuploading but just reusing the existing AMI.
Use the correct snapshot name to ensure that --force works.
- cmd/plume: Only build Azure Pro for LTS
- cmd/ore: Add new "aws delete" command to remove an image
An image uploaded by "ore aws upload" could only be deleted manually.
Add a subcommand to delete the image again.
In conjunction with https://github.com/kinvolk/flatcar-scripts/pull/106 and from Jenkins.
Tested only uploading and …
> Improve AWS subcommands in ore, support AWS Pro downloading in cork, adjust LTS handling in plume

- cmd/cork/downloadimage.go
The location where the image is placed may not have a version.txt file.
> cmd/cork/downloadimage: Make check for version.txt optional

- kola/tests/misc/network.go
The CRI plugin listens on a random port to serve the streaming API.
> kola/tests/misc/network.go: Allow the containerd CRI plugin to listen

- cmd/plume/containerlinux.go
This does not work at the moment and will only be done for GCE Pro.
> cmd/plume: Don't try to publish GCE LTS images

- kola/tests/docker/docker.go
CI should run docker run with options together like `--cpu-quota=1000 --cpu-period=1000`.
That's because usually `--cpu-period` should work with `--cpu-quota`, as mentioned in https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources.
That will fix an issue of docker run hanging for a long time, when running with the systemd cgroup driver.
> kola: fix cgroup parameters for docker

- kola/tests/misc/network.go
As local DNS server systemd-resolved listens on 127.0.0.53:53 accepting
both TCP and UDP connections. It should be used not only for its caching
and other features but because otherwise the per-interface DNS servers
get merged into one global /etc/resolve.conf file.
See https://github.com/kinvolk/Flatcar/issues/285
```
wget https://storage.googleapis.com/flatcar-jenkins/developer/developer/boards/amd64-usr/2020.12.07+dev-flatcar-master-1604/flatcar_production_qemu_image.img.bz2
lbunzip2 flatcar_production_qemu_image.img.bz2
sudo ./kola run --board=amd64-usr --channel=alpha --parallel=1 --platform=qemu --qemu-bios=bios-256k.bin --qemu-image flatcar_production_qemu_image.img cl.network.listeners
```
> kola/tests/misc/network.go: Allow systemd-resolved to run

- cmd/cork/create.go
- kola/README.md
- kola/tests/docker/docker.go
Repositories were moved to the kinvolk org.
> Update git URLs

- kola/tests/docker/torcx_docker_flag.go
Since the Docker 1.12 will be soon removed from Alpha, we need to exclude `alpha` from the list of channels, where tests run on hard-coded strings for Docker 1.12 in torcx profiles.
> kola: do not test Docker torcx profile tests for alpha

- kola/tests/flannel/flannel.go
In case flanneld restarted, it does not work anymore to ping its
bridge address .0/32 attached to the flannel0 interface but only the
other addresses like .1/24 on docker0. This is the case with rkt
already but now with docker we have an additional restart of flanneld
when docker gets restarted to apply the flannel settings. Now this
problem directly pops up but before it would normally not happen in
the test.
Run kola test `cl.flannel.udp` on Equinix Metal or another cloud platform (not QEMU)
> kola/tests/flannel: use docker0's interface address as destination

- sdk/repo.go
When no git configuration is found in the SDK chroot, git will error
out because it can't set the committer when applying the patches.
Always specify a default committer for applying patches.
Follow-up after https://github.com/kinvolk/mantle/pull/163
Tested by running and checking the commit with `git show --format=full` to show `Commit: Flatcar Buildbot …`
> cork: Apply patches with a dummy committer

- kola/tests/docker/torcx_docker_flag.go
WIth the Alpha to Beta transition, Docker 1.12 is removed from Beta, and we would need to remove the beta from testing Docker 1.12 torcx profiles.
> kola: Exclude beta from Docker torcx profiles tests

- kola/README.md
Current example use `rhcos` which can leads to error when testing for container linux
> kola/readme: update example to use container linux

- kola/tests/etcd/discovery.go
- kola/tests/flannel/flannel.go
- kola/tests/ignition/security.go
- kola/tests/locksmith/locksmith.go
- platform/local/dnsmasq.go
- platform/local/flight.go
- platform/machine/esx/cluster.go
- platform/machine/qemu/cluster.go
-  platform: allow CLC templating for dynamic IP address insertion
The tests that require coreos-metadata and CLC templating could not
run because for QEMU only a static replacement was done before the
CLC configuration was rendered.
Add support for the template variables by treating QEMU as a custom
platform for the transpiler, making use of a coreos-metadata service
that has the IP addresses hardcoded.
- platform/machine/*/cluster.go: update custom coreos-metadata service
The coreos-metadata service in the Flatcar OEMs normally writes to
a "flatcar" file and symlinks it.
Do the same for the custom ESX and QEMU coreos-metadata services.
- platform/local/dnsmasq: hardcode DNS server for QEMU tests
The system may have 127.0.0.53 as DNS server which is the
systemd-resolved stub. This is no …
> platform: allow CLC templating for dynamic IP address insertion

- kola/tests/rkt/rkt.go
When rkt is dropped from the Alpha image, the test will fail.
It can be kept for the other channels as long as they have rkt.
> kola/tests/rkt: remove the rkt test from running on Alpha

- kola/tests/kubernetes/basic.go
- kola/tests/kubernetes/controllerInstall.go
- kola/tests/kubernetes/setup.go
- kola/tests/kubernetes/workerInstall.go
- platform/qemu.go
in this PR, we remove the usage of `rkt` runtime and the `kubelet-wrapper` in order to prepare the removal of this components from the OS.
It could run on `QEMU` but I have some memory issues. Tests have been done on `GCP` using `alpha-2823.0.0`: 
```
./bin/kola run --basename=${BASENAME} \
--gce-image=${IMAGE_NAME} \
--gce-json-key=${GCE_JSON_KEY} \
--parallel=4 --platform=gce \
-d -k --remove=false \
${TEST_NAME}
2021-04-22T12:30:43Z cli: Started logging at level DEBUG
=== RUN   google.kubernetes.basic.docker.v1.18.0
2021-04-22T12:30:43Z kola/tests/kubernetes: Creating single-node etcd
2021-04-22T12:30:43Z platform/api/gcloud: Creating instance "tormath1-tests-rkt-68160e03b7993c51b9a5"
2021-04-22T12:31:05Z platform/api/gcloud: Created instance "tormath1-tests-rkt-68160e03b7993c51b9a5" …
```
> remove rkt and kubelet-wrapper from kubernetes tests

- kola/registry/registry.go
- kola/tests/kubeadm/kubeadm.go
- kola/tests/kubeadm/kubeadm_test.go
- kola/tests/kubeadm/templates.go
In this PR, we add kubernetes tests using `kubeadm` and `ignition` to setup the cluster.
A `user-data` script will be uploaded through ignition on both worker and controller in order to run the required commands. `ignition` will take care of pulling required binaries / uploading various files (user-data, manifest).
Test will assert that there is two running nodes and it will deploy a nginx pod.
```
./build kola
```
It has been tested on `qemu` platform with `alpha-2823.0.0`:
```bash
$ sudo ./bin/kola run -b cl -p qemu --qemu-image flatcar_production_qemu_image.img kubeadm.base
=== RUN   kubeadm.base
=== RUN   kubeadm.base/node_readiness
=== RUN   kubeadm.base/nginx_deployment
--- PASS: kubeadm.base (317.05s)
cluster.go:117: Created symlink …
```
> kola: add kubeadm tests

- kola/tests/kubeadm/kubeadm.go
kola/kubeadm: exclude esx from tested platforms
ESX tests are failing on Jenkins with this message:
```
not ok - kubeadm.base
Error: "kubeadm.go:80: unable to setup cluster: unable
to create master node: getting machine info: waiting for net
ip: Post \"https://w.x.y.z/sdk\": context deadline exceeded"
```
which seems to be an error related to the provider itself
> kola/kubeadm: exclude esx from tested platforms

- kola/tests/kubeadm/kubeadm.go
tests are currently failing - we exclude them to take some time to
properly identify the underlying issue.
controller node spams a lot of FlexVolume related error:
```shell
May 17 07:54:56.409708 kubelet[2807]: W0517 07:54:56.409706    2807 driver-call.go:149] FlexVolume: driver call failed: executable: /opt/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds, args: [init], error: fork/exec /opt/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds: no such file or directory, output: ""
May 17 07:54:56.413207 kubelet[2807]: E0517 07:54:56.413152    2807 plugins.go:748] Error dynamically probing plugins: Error creating Flexvolume plugin from directory nodeagent~uds, skipping. Error: unexpected end of JSON input
```
and from the worker node:
```shell
May 17 …
```
> kola/kubeadm: exclude azure platform

- kola/tests/kubeadm/kubeadm.go
Update containernetworking/plugins to v0.8.7, mainly to address [CVE-2020-10749](https://nvd.nist.gov/vuln/detail/CVE-2020-10749) .
> kola: update containernetworking/plugins to v0.8.7

- kola/tests/kubeadm/kubeadm.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubernetes/basic.go
- kola/tests/kubernetes/controllerInstall.go
- kola/tests/kubernetes/workerInstall.go
In this PR, we try to get `kubeadm` tests working on Azure.
- issue when we fetch the IP based on `/run/metadata/flatcar`
I investigated on other potential issues but it seems OK now. I had a doubt with some hardcoded _time to live_ for the created instances but nothing in the code.
```
./bin/kola run --board=amd64-usr --channel=stable --platform=azure ... kubeadm.base
```
(ran twice in a row)
closes https://github.com/kinvolk/Flatcar/issues/399
> kubernetes and kubeadm tests: make it work on azure

- kola/tests/docker/docker.go
`selinux` support is going to be disabled on the next shipped Docker.
To keep compatibility with current releases, selinux is made optional:
we just assert that at least `seccomp` or `selinux` or both are
enabled.
this commit will be reverted once SELinux will be back on Flatcar
> kola/docker: make selinux optional

- kola/tests/misc/files.go
On arm64, we have a `/run/udev/data/+platform:Fixed MDIO bus.0`, which, due to the presence of spaces in the filename. Since `/run` is an ephemeral directory and we skip other directories (`/proc`, `/sys`) for that reason, it seems like a good idea to skip `/run` as well.
> tests/cl.filesystem: skip "/run", fix test failure on arm64

- kola/tests/rkt/rkt.go
Signed-off-by: Sayan Chowdhury <sayan@kinvolk.io>
rkt has been deprecation is promoted to Beta, so the tests need to be removed.
```
> ./bin/kola list --channel stable --filter "*rkt*"
Test Name	Platforms	Architectures	Distributions	Channels		Offerings
cl.rkt.etcd3	[all]		[all]		[cl]		[stable edge lts]	[all]
rkt.base	[all]		[all]		[cl]		[stable edge lts]	[all]
> ./bin/kola list --channel beta --filter "*rkt*"
Test Name	Platforms	Architectures	Distributions	ChannelsOfferings
```
> kola/tests: Exclude rkt tests from alpha & beta channels

- sdk/enter.go
- system/symlink.go
In WSL2 /dev/shm is a symlink to /run/shm. cork has code to handle that but that code didn't work correctly and resulted in "permission denied" errors when entering the SDK chroot.
`cork create` in a WSL2 terminal.
`cork create`, checked that no errors occur, and then `cork enter` and checked that /run/shm
1. exists
2. has the sticky bit set
by running `ls -ld /run/shm` in the chroot.
> cork: fix handling of /dev/shm -> /run/shm symlinks

- platform/util.go
By default, all kola tests `setenforce 1`. This change allows user to read SELinux AVC logs from kola logs - Flatcar prevents natively AVC logs gathering (https://github.com/kinvolk/coreos-overlay/blob/main/sys-process/audit/files/rules.d/80-selinux.rules)
It will ease to identify SELinux related errors.
before
```bash
cat _kola_temp/qemu-2021-06-22-1518-657712/docker.torcx-manifest-pkgs/151167d1-5fde-4862-93bc-312debdd4814/console.txt
...
[  167.267644] IPv6: ADDRCONF(NETDEV_CHANGE): veth1cda38f: link becomes ready
[  167.269177] docker0: port 1(veth1cda38f) entered blocking state
[  167.270341] docker0: port 1(veth1cda38f) entered forwarding state
[  167.350524] docker0: port 1(veth1cda38f) entered disabled state
[  167.352651] vethfac6db4: renamed from eth0
[  167.370865] docker0: port …
```
> platform/util: enable selinux logs for SELinux tests

- platform/qemu.go
Kola output is littered with warnings about auto-detection of backing image format, this PR deals with those.
`./build_image` + `kola run`.
`kola run` before and after, and verified that warnings about backing_fmt gone.
> platform/qemu: specify raw backing_fmt explicitly

- cmd/kola/options.go
- cmd/ore/packet/packet.go
- platform/api/packet/api.go
- platform/flight.go
- platform/machine/aws/machine.go
- platform/machine/azure/machine.go
- platform/machine/do/machine.go
- platform/machine/esx/machine.go
- platform/machine/gcloud/machine.go
- platform/machine/openstack/machine.go
- platform/machine/packet/machine.go
- platform/machine/qemu/flight.go
- platform/machine/qemu/machine.go
- platform/machine/unprivqemu/machine.go
- platform/platform.go
- platform/util.go
`board` is accessible only for Packet and QEMU machines. It can be helpful to get this value for other machine in order to do some conditional operation in the setup - like enforcing SELinux. See: https://github.com/kinvolk/mantle/pull/180#issuecomment-875497624.
In this PR, we provide a new `Board () string` method to the `Machine` interface.
`Board()` returns value from a new base options implemented in `platform.Options`. We currently need to use the `syncoptions`  method to pass the value of the `board` to each provider - this one is provided by the `--board` flag bound to the `kola.QEMUOptions.Board`
Based on the `options.Board` we now conditionally enable SELinux on the machine.
> platform: provide Board access to the runtime

- kola/tests/docker/docker.go
Docker 20 with cgroupv2 reports "seccomp" and "cgroupns" security options. Allow both in the tests that check security options, which will work with current images and future images.
> kola/docker: accept 'cgroupns' security option

- kola/tests/util/update.go
The switch from coreos-setgoodroot to flatcar-setgoodroot was done for
cmd/kola/updatepayload.go but not yet for kola/tests/util/update.go.
Use flatcar-setgoodroot which is the new name.
Together with https://github.com/kinvolk/flatcar-scripts/pull/130
`sudo kola run …run -k -d --board=amd64-usr --platform=qemu --qemu-image=tmp/flatcar_production_qemu_image.img  --update-payload=tmp/flatcar_test_update.gz cl.update.payload`
```
--- PASS: cl.update.payload (209.74s)
cluster.go:117: Created symlink /etc/systemd/system/locksmithd.service → /dev/null.
update.go:149: Triggering update_engine
update.go:168: Rebooting test machine
update.go:149: Triggering update_engine
update.go:168: Rebooting test machine
PASS, output in _kola_temp/qemu-2021-07-12-1957-2564530
```
> kola/tests/util/update: use correct command name

- kola/tests/update/update.go
The 2 minute timeout was too short on arm64 qemu emulation for
completing the update.
Increase the timeout to 10 minutes.
```
sudo ./kola run --board=arm64-usr --channel=alpha --platform=qemu  --update-payload=tmp/flatcar_test_update.gz --qemu-bios=tmp/flatcar_production_qemu_uefi_efi_code.fd --qemu-image=tmp/flatcar_production_image.bin cl.update.payload
=== RUN   cl.update.payload
--- PASS: cl.update.payload (1032.33s)
cluster.go:117: Created symlink /etc/systemd/system/locksmithd.service → /dev/null.
update.go:149: Triggering update_engine
update.go:168: Rebooting test machine
update.go:149: Triggering update_engine
update.go:168: Rebooting test machine
PASS, output in _kola_temp/qemu-2021-07-14-1931-2822851
```
> kola/tests/update: increase update timeout for arm64

- kola/tests/misc/verity.go
- kola/tests/verity: fall back to expected dm-verity offset
When e2size can't find the size it returns an error exit code and
stdout stays empty, failing the test. However, the hash offset is
actually fixed because the GPT disk layout has to stay the same in
Flatcar Container Linux as the partition contents are swapped out
when updating. In case another filesystem like btrfs is used, e2size
doesn't work and it makes sense to fall back to the only value which
is supported in general.
- kola/tests/verity: skip the corruption test for btrfs
The corruption test corrupts a particular file and checks that read
syscalls for this file fail. With btrfs is is not easy to find the
right block to corrupt. It is also currently discussed to issue a
kernel panic on corruption because failed read …
> kola/tests/verity: fall back to expected dm-verity offset

- kola/tests/update/update.go
the instance is currently configured once to be able to use
the `update_payload`.
Once the payload downloaded and the instance rebooted, kola
is going to download again an update: in the case we previously
downloaded and installed an official release, the
/usr/share/update-engine/pub-key will be changed to the official one.
So update-engine will fail to verify the new update payload since this
one appears to be signed only with a dev-key (it's generated from
the SDK.)
So we reconfigure again to inject the dev-pub-key to verify correctly
the downloaded payload
> kola/test/update: reconfigure the instance once rebooted

- kola/tests/rkt/rkt.go
`rkt` won't be present in the next `stable` release, we can safely exclude rkt tests
from this channel
> kola/tests/rkt: exclude `stable` channel

- kola/tests/docker/torcx_docker_flag.go
docker 1.12 is not shipped anymore on next `stable`.
See: https://github.com/kinvolk/coreos-overlay/commit/787353d775a103b3d3017aa12f02635636a30070
(sorry for the spam I could have group this with the previous PR)
> kola/tests/docker: exclude `stable` from torcx

- kola/tests/kubeadm/kubeadm.go
- kola/tests/kubeadm/kubeadm_test.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
- kola/tests/kubeadm/testdata/master-cilium-script.sh
- kola/tests/kubeadm/testdata/master-flannel-script.sh
In this PR, we try to cover more kubernetes use cases by testing different CNIs.
- flannel
- calico
- cilium
```
$ ./bin/kola list | grep kubeadm
kubeadm.calico.base			[aws azure do gce openstack packet qemu qemu-unpriv]	[all]		[cl]		[all]			[all]
kubeadm.cilium.base			[aws azure do gce openstack packet qemu qemu-unpriv]	[all]		[cl]		[all]			[all]
kubeadm.flannel.base			[aws azure do gce openstack packet qemu qemu-unpriv]	[all]		[cl]		[all]			[all]
$ sudo ./bin/kola run -b cl -p qemu --qemu-image ./flatcar_production_qemu_image.img kubeadm.flannel.base
```
closes: https://github.com/kinvolk/Flatcar/issues/309
> kola/kubeadm: test various CNIs

- kola/harness.go
- kola/register/register.go
- kola/tests/misc/update.go
- kola/tests/misc/verity.go
The dm-verity behavior was to only let some syscalls fail but it let
the system run in a broken state. By enabling kernel panics on
corruption detection we get a more reasonable behavior. This change is
done in https://github.com/kinvolk/bootengine/pull/26
To support the new behavior the test that do corrupt on purpose need to
be flagged to be excluded from the kernel panic checks. The corruption
test also shouldn't test for a failed syscall anymore but expect the
kernel panic to render the machine unreachable.
Implement the test flag to ignore kernel panics on the console and
modify the corruption test to fit the new behavior, which also makes
the test easier because it doesn't need to find the exact file to
corrupt and we can destroy the filesystem metadata and then try to read
any …
> Expect kernel panic when dm-verity detects corruption

- kola/harness.go
- kola/tests/misc/verity.go
- kola: support nightly version in version comparions
The nightly version is the build date but the build ID has the branch
reference. To support the version comparion for nightly builds we need
to generate a version for the "main" branch and the major version
branches that is higher than the current release version.
Use 999999.99.99 as version in the semantic version checks for nightly
builds from the "main" branch or custom dev builds and use MAJOR.99.99
as version for nightly builds from the release branch.
- kola/tests/misc/verity: run test based on major version
```
$ sudo ./kola run  -k --keys --key ~/.ssh/id_rsa.pub --board=amd64-usr --channel=alpha --parallel=1 --platform=qemu    --qemu-image=flatcar_production_image.bin
2021-08-02T15:25:15Z kola: Using "999999.99.99" as version …
```
> kola: support nightly version in version comparisons

- kola/tests/docker/docker.go
we create a simple scenario where the user would run a docker container
with a shared volume within SELinux context.
:warning: can't be run with current Flatcar release as it needs SELinux updates
```
sudo ./bin/kola run -b cl -p qemu --qemu-image flatcar_production_qemu_image.img docker.selinux
```
closes https://github.com/kinvolk/Flatcar/issues/304
> kola/docker: add selinux test

- kola/harness.go
The LTS branch is flatcar-lts-MAJOR and only flatcar-MAJOR branch names
were considered which let to an invalid major version "lts" being
parsed.
Take the element after either "flatcar" or "flatcar-lts" when splitting
on "-". The full build ID is "dev-flatcar(-lts)-MAJOR-nightly-XYZ".
Tested with a nightly build for `flatcar-2955`
> kola/harness: detect LTS major version

- kola/tests/docker/docker.go
- kola/tests/kubernetes/basic.go
docker 1.9 and kubernetes <1.19 are not compatible with docker 20 that we are rolling into alpha. These tests need to be excluded, to be removed later.
Fetch the image from http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/3035/ and run test (`kola run`)
`kola run`
See also kinvolk/coreos-overlay#931
> kola/test: disable tests that won't work with docker 20.10

- kola/tests/misc/verity.go
On amd64 the panic was triggered by the 'cat' execution as expected
but on arm64 through QEMU emulation the kernel panic took a while to
be triggered. It seems the most reliable way is to walk the filesystem.
Add a recursive list to provoke the panic on arm64 if it didn't get
triggered by the simple 'cat' file reading.
`sudo ./kola run -d -k --keys --key ~/.ssh/id_rsa.pub --board=arm64-usr --channel=alpha --parallel=1 --platform=qemu    --qemu-image=flatcar_production_image.bin   --qemu-bios=…/flatcar_production_qemu_uefi_efi_code.fd cl.verity`
> kola/tests/misc/verity: add recursive list to provoke panic

- kola/tests/kubeadm/kubeadm.go
register action was keeping the latest occurence of `CNI` so it was
basically always testing the `cilium` CNI.
... it happens.
The issue was already being fixed into #196 but it's better to be merged now to confirm that https://github.com/kinvolk/coreos-overlay/pull/1181 is solving the actual `flannel` issue raised in https://github.com/kinvolk/mantle/pull/196#issuecomment-895358491
> kola/kubeadm: fix CNI selection

- build
The `-i` flag is deprecated for `go build` in newer compiler versions
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
> build: remove deprecated flags

- kola/tests/kubeadm/kubeadm.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
- kola/tests/kubeadm/testdata/master-cilium-script.sh
- kola/tests/kubeadm/testdata/master-flannel-script.sh
this commit brings a new release of kubernetes to test but it also fixes
a `TODO:`. We are now able to provide multiple kubernetes release to
test.
We just need to create a new `map[string]interface{}` holding the
params of the kubernetes release we want to test.
```
$ ./bin/kola list
kubeadm.v1.21.0.calico.base
kubeadm.v1.21.0.cilium.base
kubeadm.v1.21.0.flannel.base
kubeadm.v1.22.0.calico.base
kubeadm.v1.22.0.cilium.base
kubeadm.v1.22.0.flannel.base
```
**note for reviewers**:
* I'm a bit concerned by the number of tests we provide now for kubernetes: versions + CNIs are creating big test matrix which can slow down the tests overall... but I guess it's the price to pay in order to identify potential failures with kubernetes workloads
> kola/kubeadm: add kubernetes 1.22 test

- kola/tests/coretest/core.go
- kola/tests/docker/docker.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubernetes/basic.go
We're hitting dockerhub pull rate limits in our CI. Most frequently it occurs with busybox and nginx images so I've mirrored those first. The nginx one is probably going to be pulled most often: the kubeadm tests run for 3 CNIs and multiple nodes each.
The mirroring was done with the following script:
```bash
#!/bin/bash
image=$1
platforms=( amd64 arm64 )
tags=()
for platform in "${platforms[@]}"; do
var=$(docker pull $image --platform=$platform -q)
tag=ghcr.io/kinvolk/$image:latest-$platform
docker tag $var $tag
docker push $tag
tags+=( $tag )
done
docker manifest create ghcr.io/kinvolk/$image:latest "${tags[@]}"
docker manifest push --purge ghcr.io/kinvolk/$image:latest
```
`./bin/kola run --channel=alpha cl.internet docker.selinux`
> kola: Use github container registry for test images

- kola/tests/misc/selinux.go
SELinux is currently not yet available on ARM64 - there is an effort
to enable SELinux in this PR: https://github.com/kinvolk/coreos-overlay/pull/135.
Since the recent SELinux upgrades, we will need to rework a bit the PR.
> kola/test/selinux: exclude `arm64` architecture

- cmd/cork/create.go
- sdk/repo.go
The messages are long and scroll by too fast to be of any use to users. Adding
quiet turns it into a nice progress indicator.
> sdk: pass '--quiet' to repo sync

- kola/tests/docker/docker.go
- platform/qemu.go
In this PR, we pull two fixes for ARM64 tests suite:
- increase the memory for QEMU tests - otherwise `torcx` was randomly failing to unpack Docker (-> no Docker)
- remove the explicit `setenforce 1` in `docker.userns` test (see the commit body for the `why?`)
> test: fixes for ARM64

- README.md
- kola/tests/etcd/discovery.go
- kola/tests/etcd/util.go
Most of the tests rely on `etcd` and use the `GetClusterHealth` method to ensure the etcd cluster is up and running. In this [PR](https://github.com/kinvolk/coreos-overlay/pull/1179); we upgraded `etcd` and it [seems](https://github.com/etcd-io/etcd/commit/25bc65794f6802cb24b40c3a46de9ab3fa5f9e6b) now the default `etcdctl` version is V3.
It should fix the following tests:
- cl.etcd-member.discovery
- cl.etcd-member.v2-backup-restore
- google.kubernetes.basic.docker.v1.18.0
- google.kubernetes.basic.docker.v1.16.8
- google.kubernetes.basic.docker.v1.14.10
- cl.locksmith.cluster
- coreos.locksmith.tls
- cl.etcd-member.etcdctlv3
- kubeadm.*
I first attended to support both v2/v3 but it becomes quickly an unmaintainable mess - so I removed the `setKeys` / `checkKeys` from the …
> etcdctl: use v3

- kola/tests/etcd/discovery.go
with `etcdctl/v3` default endpoints is: 127.0.0.1:2379 while with
`etcdct/v2` it's http://127.0.0.1:2379,http://127.0.0.1:4001.
`etcdct/v3` was failing to reach `127.0.0.1:2379` because it's bound
to the private IPv4 (so `10.0.0.x`) (see also other tests: https://github.com/kinvolk/mantle/blob/flatcar-master/kola/tests/etcd/discovery.go#L35)
```
git checkout tormath1/fix-etcd-v2-restore
./build kola
sudo ./bin/kola run ...  cl.etcd-member.v2-backup-restore
```
:arrow_up:
> kola/tests/etcd: bind :2379 on all interfaces

- kola/tests/etcd/discovery.go
- kola/tests/flannel/flannel.go
- kola/tests/locksmith/locksmith.go
In this PR, we prepare the landing of https://github.com/kinvolk/coreos-overlay/pull/1179 which brings `etcd/v3` by default.
- `flannel` does not support yet `etcd/v3` so we enable `v2` support
- `locksmith` is [WIP](https://github.com/kinvolk/locksmith/pull/12) to support `etcd/v3`
- `cl.etcd-member.v2-backup-restore` test the actual behavior of `v2` backup so it requires `v2` to be enabled
`v2` support is done through this option: https://etcd.io/docs/v3.5/op-guide/configuration/#--enable-v2
Tested against the current `alpha` and the image provided in https://github.com/kinvolk/coreos-overlay/pull/1179 (arm64 in progress...)
```
sudo ./bin/kola run ... cl.etcd-member.v2-backup-restore cl.locksmith.cluster coreos.locksmith.tls cl.flannel.udp cl.flannel.vxlan
```
> etcd: enable `v2` support for various tests

- CHANGELOG.md
- kola/tests/misc/selinux.go
- platform/util.go
Since `arm64` is going to support `SELinux`, there is no more need to not enable SELinux for `arm64` in the tests runtime.
Note: all the test will enable SELinux for `arm64`, we need to find a way to prevent channel != alpha to enable SELinux, otherwise all tests will fail until `SELinux/arm64` lands into `stable`.
related to: https://github.com/kinvolk/coreos-overlay/pull/1245
n/a
> plaform/util: enable SELinux for all arch

- README.md
This PR brings a bit of documentation in order to help contributors / maintainers to run local tests using `QEMU` for both architectures (`arm64` and `amd64`)
* download and install `kola`
* list of requirements
* run tests on both architectures
_note_: no changelog entry since it's not a noticeable change for mantle itself
> `readme`: add a `getting started` section

- CHANGELOG.md
- kola/tests/docker/docker.go
SELinux is now supported on ARM64
```
wget https://storage.googleapis.com/flatcar-jenkins/developer/developer/boards/arm64-usr/2021.09.01%2Bdev-flatcar-master-3470/flatcar_production_image.bin.bz2
sudo ./bin/kola run --channel alpha --board arm64-usr --key ${HOME}/.ssh/id_rsa.pub -k -b cl --qemu-bios ./flatcar_production_qemu_uefi_efi_code.fd  -p qemu --qemu-image ./flatcar_production_image.bin docker.selinux
```
> kola/test/docker: enable `docker.selinux` for all arch

- CHANGELOG.md
- kola/tests/etcd/discovery.go
- kola/tests/flannel/flannel.go
- kola/tests/locksmith/locksmith.go
In 12b5a96ee4099cc3c2dbe4af35ebbfc55b13868a, we enabled the V2 support
for `etcd`. It means that `etcd` starts with support for both datastore
version.
Support has been enabled through a `systemd` dropin - this one will
generate a dropin under the `etcd-member.service` unit but
`container-linux-config` will generate a dropin under
`etcd-member.service` name too.
This is not an issue with `ignition/v2` but it is with `ignition/v3`
(see: https://github.com/kinvolk/ignition/blob/main/docs/configuration-v3_0.md).
So we need to add the `enable_v2` direcly into the `clc` - `enable_v2`
is present in `clc` from `config.Types.Etcd3_2` but by default it
targets `3.0.0` so we need to pin the version to the current tested one
(`3.5.0`) to use `enable_v2` and the correct image tag.
Signed-off-by: …
> kola/test: use clc to set `enable_v2`

- CHANGELOG.md
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-cilium-amd64-config.yml
- kola/tests/kubeadm/testdata/master-cilium-arm64-config.yml
this can help debugging failing tests.
See also: https://docs.docker.com/config/containers/logging/journald/
For ARM64, tests are failing and only indications we have are from kubelet:
```
Sep  7 09:22:43.120921 kubelet[1354]: E0907 09:22:43.120852    1354 pod_workers.go:747] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"ebpf-mount\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=ebpf-mount pod=cilium-g84j6_kube-system(aa57d085-b710-4447-b704-550e59266eee)\"" pod="kube-system/cilium-g84j6" podUID=aa57d085-b710-4447-b704-550e59266eee
```
- run a `kubeadm.*` test
- check logs into `_kola_temp/.../journal.txt`:
```shell
Sep  7 15:41:10.780613 kernel: IPVS: [rr] scheduler registered.
Sep …
```
> kola/kubeadm/tmpl: forward docker logs to journald

- kola/tests/misc/network.go
Starting from systemd-v249, some services description have changed which leads to
test failure since we rely on the exact string matches for this test.
Note: I don't think a changelog entry is relevant for this change.
> kola/misc/network: support various network service description

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
`etcd` type from `clc` takes care of enabling the `etcd-member` unit -
there is no need to enable it "manually".
It's not an issue with `ignition/v2` but `ignition/v3` does not like
duplicate systemd dropin entries.
See: https://github.com/kinvolk/container-linux-config-transpiler/blob/flatcar-master/config/types/etcd.go#L136-L137
> kola/test/kubeadm: remove duplicate etcd-member entry

- CHANGELOG.md
- kola/tests/ignition/oem.go
In this PR, we try to test the usage of OEM - which is too required to run tests for the "new" ignition(v2/v3)
Closes: https://github.com/flatcar-linux/Flatcar/issues/486
Three tests:
* try to reuse the partition using a `btrfs` format
* try to reuse the parition using `ext4` format
* wipe the partition by using `wipeFilesystem`
```
$ ./bin/kola list | grep oem
cl.ignition.oem.regular			[all]								[all]		[cl]		[all]		[all]
cl.ignition.oem.reuse			[all]								[all]		[cl]		[all]		[all]
cl.ignition.oem.wipe			[all]								[all]		[all]		[all]		[all]
```
Only on `qemu`.
> kola/test/oem: add ignition OEM test

- kola/tests/ignition/oem.go
`wiping` the OEM file system does not allow the instance to boot. Let's
exclude the platform while we proceed to further investigations.
Related-to: https://github.com/flatcar-linux/Flatcar/issues/514
> kola/ignition/oem: exclude `esx` and `azure` from platforms

- CHANGELOG.md
- kola/tests/misc/raid.go
`size` has been deprecated to `sizeMiB` from `ignition-2.3` and this
parameter is not translatable. See the discussion in here: https://github.com/coreos/ign-converter/pull/29
Since CLC is converted to `ignition-2.2` we can't rely on this to pass
the config so we directly use raw ignition 2.3.0 to provision the
instance.
This test only runs on `qemu` so there is no side effect to pass from
`clc` to `ignition`.
Tested against:
* alpha-2983.0.0
* image with ignition/v3 from: https://github.com/flatcar-linux/coreos-overlay/pull/1249
> kola/misc/raid: change CLC to raw ignition config

- CHANGELOG.md
- cmd/cork/create.go
- cmd/cork/download.go
- sdk/download.go
In this PR, we add the `--json-key` flag to `create` and `download` subcommands from `cork`. It allows a user to pass a GCS credential file path to `cork` in order to download from a private GCS bucket.
`update` command use the flags from the creation flags set, so no need to update this part:
```go
updateCmd.Flags().AddFlagSet(creationFlags)
```
```
$ ./bin/cork create --verbose --sdk-url-path "/flatcar-jenkins/sdk"
2021-10-04T16:11:35Z cli: Started logging at level INFO
2021-10-04T16:11:35Z cork: Detecting SDK version
2021-10-04T16:11:36Z cork: Found SDK version 3005.0.0 from remote repo
2021-10-04T16:11:36Z cork: Downloading SDK version 3005.0.0
2021-10-04T16:11:36Z sdk: Downloading https://storage.googleapis.com/flatcar-jenkins/sdk/amd64/3005.0.0/flatcar-sdk-amd64-3005.0.0.tar.bz2 to …
```
> `cork`: add `--json-key` to `create` and `download`

- CHANGELOG.md
- cmd/cork/create.go
- cmd/cork/download.go
- sdk/download.go
This PR superseeds #238 - we add a new flag `--sdk-url` in order to provide more flexibility.
It defaults to `mirror.release.flatcar-linux.net` for the UX.
```
$ ./bin/cork create --verbose
2021-10-05T10:42:14Z cli: Started logging at level INFO
2021-10-05T10:42:14Z cork: Detecting SDK version
2021-10-05T10:42:14Z cork: Found SDK version 3005.0.0 from remote repo
2021-10-05T10:42:14Z cork: Downloading SDK version 3005.0.0
2021-10-05T10:42:14Z sdk: Downloading https://mirror.release.flatcar-linux.net/sdk/amd64/3005.0.0/flatcar-sdk-amd64-3005.0.0.tar.bz2 to /home/mathieu/go/src/github.com/kinvolk/mantle/.cache/sdks/flatcar-sdk-amd64-3005.0.0.tar.bz2
2021-10-05T10:42:14Z sdk: Resuming from byte 7405568
^Catcar-sdk-amd64-3005.0.0.tar.bz2: [                          ] 23.5 MB/1.36 GB
$ …
```
> cork: add `--sdk-url`

- CHANGELOG.md
> changelog: bump to 0.17.0

- CHANGELOG.md
- cmd/plume/containerlinux.go
Without this the pre-release step for the Beta channel would fail, and no kola tests can be done.
Signed-off-by: Sayan Chowdhury <schowdhury@microsoft.com>
Not tested, but built locally.
> plume: Enable the ARM64 board for Beta channel

- CHANGELOG.md
- platform/cluster.go
- platform/util.go
In this PR, we enable SELinux in enforcing mode earlier in the boot. Previously, it was done once the instance booted by running `sudo setenforce 1`.
By enabling and running all the tests with `enforcing` mode set as soon as possible during the boot, we'll be able to catch early denial from SElinux (like this one: https://github.com/flatcar-linux/coreos-overlay/pull/1426) which can prevent Flatcar to behave correctly.
```
$ ./build kola
$ sudo ./bin/kola spawn --qemu-image ./flatcar_production_qemu_image.img
[bound] core@localhost ~ $ getenforce
Enforcing
[bound] core@localhost ~ $ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             mcs
Current mode: …
```
> platform: enable enforcing mode SELinux earlier

- platform/cluster.go
- platform/conf/conf.go
Some tests use machines without userdata and in this case there is no
way to inject it and the test should rather use a minimal dummy
Ignition config to enforce SELinux if it's relevant.
Don't try to inject SELinux enforcement in case no userdata is present
because the function panics in this case.
Should fix the panic for `systemd.journal.remote`
`make test`
> RenderUserData: only incject SELinux enforcing if there is userdata

- CHANGELOG.md
- platform/cluster.go
- platform/conf/conf.go
- platform/util.go
In this PR, we remove the patches introduced in:
* #252 
* #253 
These patches force the usage of enforced SELinux earlier in the boot to cover more processes.
We need to remove them temporary due to this kind of error:
> Error: "cluster.go:117: The program docker is managed by torcx, which did not run.\n        cluster.go:130: \"sudo mkdir /etc/misc && \\\\\\ndocker run -v \\\"/etc/misc:/opt\\\" --rm ghcr.io/kinvolk/busybox true\" failed: output , status Process exited with status 1"
which should be fixed by https://github.com/flatcar-linux/coreos-overlay/commit/9380a02531873ba7f92805f6faf9c7ccc9008e7c but for an unknown reason yet it does not work as expected.
> platform: revert early enforced SELinux

- CHANGELOG.md
- platform/api/packet/api.go
`baremetal_0/t1.small` servers are now deprecated and no more available
in facilities.
We update to a newer server spec by default: `c3.small.x86`
See also: https://metal.equinix.com/developers/docs/servers/server-specs/#server-specs
> api/packet: change default server spec

- CHANGELOG.md
- platform/api/packet/api.go
`c2.large.arm` are deprecated too and CI is failing with:
```
2021-11-22T09:31:56Z kola: creating new machine for semver check: couldn't create device: POST https://api.packet.net/projects/2c850bb4-70b4-4dcd-b60f-2d0be86d0ae4/devices: 422 No available servers with plan c2.large.arm in facility sv15
```
`c2.large.arm` is deprecated in favor of: `c3.large.arm`.
See also: https://metal.equinix.com/developers/docs/servers/server-specs/#c3largearm
> api/packet: change default ARM server

- CHANGELOG.md
- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
- cmd/plume/release.go
- storage/bucket.go
- storage/bucket_test.go
The image download from the bucket is not possible anymore directly but
needs to be done through the HTTP proxy.  
Create a limited bucket object for anonymous access, which can only
download particular files and has no listing or	upload ability.
Calling code needs to make sure it only tries uploads or directory
listings when the bucket object is using a proper gs:// URL and that
it configured credentials before trying to upload.
```
bin/plume pre-release --gce-json-key none --aws-credentials /dev/null --platform aws -d --version 2983.2.0 --channel stable -P china
```
> plume: Use the public bucket proxy for anonymous access

- platform/api/packet/api.go
Some instance types like the c3.large.arm have only a single NVMe disk
and the installer waits endlessly for /dev/sda while it's not required.
Remove the waiting for /dev/sda from the installer service unit and
make it be restarted in case of errors, like not having found a
suitable disk.
See that a test can run on c3.large.arm
This here passed fine:
```
./kola run -k -d --basename=jenkins-831 --board=arm64-usr --channel=beta --gce-json-key=… --packet-api-key=… --packet-facility=da11 --packet-image-url=https://bucket.release.flatcar-linux.net/flatcar-jenkins/beta/boards/arm64-usr/3033.1.1/flatcar_production_packet_image.bin.bz2 --packet-installer-image-kernel-url=http://bucket.release.flatcar-linux.net/flatcar-jenkins/beta/boards/arm64-usr/3033.1.1/flatcar_production_pxe.vmlinuz …
```
> Equinix Metal: Don't wait for /dev/sda when installing

- CHANGELOG.md
- kola/registry/registry.go
- kola/tests/bpf/local-gadget.go
- kola/tests/docker/docker.go
In this PR, we test `IG` and related BPF features on Flatcar with `local-gadget` starting with DNS gadget.
We basically install `local-gadget` and prepare its run using CLC.
It currently runs without SELinux due to this: https://github.com/flatcar-linux/Flatcar/issues/509
```
./build kola
./bin/kola list | grep gadget
bpf.local-gadget			[all]								[all]		[cl]		[all]		[all]
```
```
=== RUN   bpf.local-gadget
=== RUN   bpf.local-gadget/dns_gadget
--- PASS: bpf.local-gadget (20.63s)
--- PASS: bpf.local-gadget/dns_gadget (18.47s)
PASS, output in _kola_temp/qemu-2021-12-01-1126-8837
```
Related-to: https://github.com/flatcar-linux/Flatcar/issues/89
It could be merged with: https://github.com/flatcar-linux/mantle/pull/233 to kickoff BPF tests on Flatcar.
> test: add bpf test with DNS gadget from local-gadget 

- CHANGELOG.md
- kola/tests/bpf/bpf.go
In this PR, we kick-off the writing of `bpf` tests.
To use it: 
```
sudo ./bin/kola run -b cl -p qemu --qemu-image ./flatcar_production_qemu_image.img bpf.execsnoop
```
Related to: https://github.com/flatcar-linux/Flatcar/issues/89
> kola/test: add `bpf` tests

- kola/tests/bpf/bpf.go
the docker image does not yet support `arm64` architecture so it fails
to run.
<hr>
No changelog entry required.
> kola/test/bpf: remove `arm64` architecture

- kola/tests/bpf/local-gadget.go
ESX initramfs does not have network access - `local-gadget` is not able
to be downloaded so the instance fails to boot.
<hr>
Changelog entry is not required.
> kola/test/bpf: remove esx from supported platforms

- CHANGELOG.md
- cmd/plume/containerlinux.go
> cmd/plume: enable `arm64` support for stable

- kola/tests/bpf/local-gadget.go
`local-gadget` Docker client does not support API < 1.41 - in the
current LTS, API VERSION is equal to 1.40.
<hr>
No changelog required
> kola/test/bpf: exclude LTS from BPF supported channel

- kola/tests/etcd/discovery.go
Using both command line option and environment variable is forbidden
since `etcd/v3`.
It happens quite a lot that user override default `etcd` name
(`machine-id`) using `CLC` through the `name: ` key.
In this case it fails because we will have both `ETCD_NAME`
and `--name` in the runtime.
This patch overrides the name in CLC in order to reproduce this behavior
and prevent regression in the next release.
<hr>
This test is currently failing with current releases - it has to be merged with https://github.com/flatcar-linux/coreos-overlay/pull/1444.
Changelog entry is not required IMHO.
> kola/tests/etcd: add `name: ` to one CLC

- CHANGELOG.md
- cmd/ore/packet/create-device.go
- platform/api/packet/api.go
- platform/machine/packet/cluster.go
- platform/machine/packet/console.go
- platform/machine/packet/flight.go
- platform/machine/packet/machine.go
In this PR, we add the ability to mantle test to reuse existing Equinix Metal instances and to keep them into a pool of devices in the Flight lifecycle.
<hr>
Closes: https://github.com/flatcar-linux/Flatcar/issues/551
> equinix-metal: recycle existing instances

- platform/machine/packet/machine.go
In case the test holds the flag `NoSSHKeyInMetadata`,
the console is not really created.
This is an issue when we destroy the machine since we try to
close the SSH console on a non-instantiated struct.
<hr>
Error has been raised in the CI:
```
--- FAIL: coreos.ignition.ssh.key (2013.61s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x16a4986]
goroutine 462 [running]:
github.com/flatcar-linux/mantle/harness.tRunner.func1(0xc00078d200)
/usr/src/myapp/harness/harness.go:407 +0x26c
panic(0x204b700, 0x382b040)
/usr/local/go/src/runtime/panic.go:965 +0x1b9 …
```
> platform/machine/em: check if console is created

- CHANGELOG.md
- cmd/kola/options.go
- cmd/plume/containerlinux.go
- platform/api/azure/api.go
- platform/api/azure/gallery-image-template.json
- platform/api/azure/image.go
- platform/api/azure/options.go
- platform/machine/azure/flight.go
This PR adds support for using gallery images on Azure. For now this is in kola only, to be used for testing. In a later step we could then move our publishing process to gallery images, which will reduce the possibility of errors when publishing on the marketplace. This would not simplify automation because the marketplace APIs only support VHD urls.
```
./bin/kola spawn --azure-auth ~/.azure/azureCredentials.json --azure-blob-url "..." --platform azure --verbose --azure-use-gallery
```
Ran `kola spawn` successfully.
> Azure gallery image support

- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
- cmd/plume/release.go
These are bugfixes for two issues that popped up after `azureBoards` was extended in #270.
1. `plume release` needs to check that the release of a channel is intended. Do this by checking for the blob existing.
2. `plume prerelease` used a blob path that did not contain the board name, collisions were possible. The name now includes the board name.
I opted for adding board to the blob name instead of doing "virtual" directories, because that way copying the blob to a machine/different directory will preserve this information.
> plume: bugfixes for release steps

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
In this PR, we add test for Kubernetes 1.23
crictl version is bumped to 1.22.0 
Ran `kubeadm.v1.23.0.cilium.base`, `kubeadm.v1.23.0.flannel.base` and `kubeadm.v1.23.0.calico.base` on EM with stable.
NOTE: calico test is skipped for Alpha (with kernel 5.15) see also this [discussion](https://matrix.to/#/!SakMJmpDOgVMlGukUp:matrix.org/$vo2kmI-qbLwTvI90N3GzdzBHH71tjSeO4nVPcv0bFAM?via=libera.chat&via=matrix.org) on Matrix
> kola/test/kubeadm: bump to kubernetes 1.23

- cmd/ore/aws/upload.go
The ore image name was defaulting to the version in contrast to plume
where we assemble a more complete name. This led to a reuse of the
amd64 EBS snapshot for arm64, or vice versa.
Add an arch suffix as done in plume (i.e., only for arm64 to keep the
existing name for amd64).
None
> ore: prevent reusing the amd64 EBS snapshot

- CHANGELOG.md
- go.mod
- go.sum
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/writesched.go
- vendor/golang.org/x/net/http2/writesched_random.go
- vendor/modules.txt
Update `golang.org/x/net` to `v0.0.0-20220114011407-0dd24b26b47d`, mainly to address [CVE-2021-44716](https://nvd.nist.gov/vuln/detail/CVE-2021-44716).
Local build passed
> go: update golang.org/x/net to v0.0.0-20220114011407-0dd24b26b47d

- CHANGELOG.md
- kola/tests/misc/files.go
Previously the entries in the directory were like `rtc/c252:0`, where
`c252:0` was just an empty file. Starting from systemd 250 it became a
dead symlink which points to `-100:/dev/rtc0`. This has caused the
`cl.filesystem` test to fail. To fix it, we add another entry to the
ignore list.
Should fix an issue like follows:
```
Error: "--- FAIL: cl.filesystem/deadlinks (0.42s)
files.go:89: Dead symbolic links found: [
/run/udev/links/disk\\x2fby-id\\x2fata-QEMU_DVD-ROM_QM00003/b11:0
/run/udev/links/disk\\x2fby-path\\x2fpci-0000:00:01.1-ata-2.0/b11:0
/run/udev/links/disk\\x2fby-path\\x2fpci-0000:00:01.1-ata-2/b11:0
…
yadda yadda yadda
]"
```
> kola: Ignore dead links in /run/udev/links

- CHANGELOG.md
- cmd/cork/create.go
- sdk/repo.go
Now that repo 2.8 is available in all Flatcar channels, the option `--repo-branch` is not needed any more.
Delete the option, and simply use the `master` branch of the git repo.
This reverts commit 071390132fb5285f907a80424f5bd806c4d90fd0.
local build passed
> cmd/cork,sdk: remove --repo-branch option from cork

- CHANGELOG.md
- kola/tests/ignition/filesystem.go
This test aims to reproduce swap activation behavior on FCL through CLC
<hr>
Related to:
* https://github.com/flatcar-linux/Flatcar/issues/133
* https://www.flatcar.org/docs/latest/setup/storage/adding-swap/#adding-swap-with-a-container-linux-config
Tested locally with Stable-3033.2.1 and Alpha-3127.0.0
> kola/test/ignition/fs: add swap_activation test

- platform/api/aws/api.go
We updated the AWS SDK and hit by a change which caused environment
credentials to be ignored when a profile is passed. Details are here[1]
Explicily set credentials to NewEnvCredentials() to make this work
again. Without this, tests fail in kola:
2022-02-04T01:19:43Z kola: creating flight for RunTests failed: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
[1]: https://github.com/aws/aws-sdk-go/issues/3382
> platform/api/aws: use env credentials when no other creds are provided

- platform/qemu.go
shortforms are deprecated from qemu-6.0.0. For tests with cloudinit config
we were getting the following warning:
```
=== RUN   cl.cloudinit.basic
qemu-system-x86_64: -fsdev local,id=cfg,security_model=none,readonly,path=_kola_temp/qemu-2022-02-10-1010-4882/cl.cloudinit.basic/65f5b234-64a4-4154-b1d9-d5168056f5e5/config-2: warning: short-form boolean option 'readonly' deprecated
Please use readonly=on instead
--- PASS: cl.cloudinit.basic (20.49s)
```
Similar to: https://github.com/flatcar-linux/scripts/pull/132
<hr>
No changelog required.
> platform/qemu: use -readonly=on

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
- kola/tests/kubeadm/kubeadm_test.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-cilium-script.sh
In this PR, we bump the cilium version to latest v1.11.0 and we give the ability to set the version from the `cilium-cli` directly, since it has been introduced in the CLI. 
This PR aims to have a more recent version of the tested cilium in order to prepare the introduction of a new test to validate the behavior of IPSec + cilium.
* tests on EM with `kubeadm.v1.23.0.cilium.base`
> kubeadm/cilium: bump tested versions

- Jenkinsfile
- platform/api/aws/ec2.go
- platform/journal.go
- platform/machine/aws/machine.go
- platform/platform.go
Several improvements to the test runtime and logging:
* instances are force stopped before terminating
* we fetch "latest" console output, which is supported on Nitro. Without the "latest" option, console output is only updated on instance lifecycle events
* reduce the timeout for new console data - the 300s timeout for updated console output  stalls almost every test case on AWS. 30s wait should be enough
* rework retry handling when establishing a journalctl connection: 120 retries, 10s delay between retries, and the ssh timeout itself meant that some failing test cases spent 6000s (!!!) before timing out. Rework with to 60 retries with a bounded timeout of 600s.
[Describe the testing you have done before submitting …
> improve aws test runtime and logging

- kola/tests/ignition/oem.go
The cl.ignition.oem.regular test sometimes fails with
"got: btrfs\nbtrfs".
Print additional information to find the cause. 
[Here](http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu_uefi/6613/console) the test got executed without hitting the failure path:
```
--- PASS: cl.ignition.oem.regular (16.27s)
```
> kola/tests/ignition/oem: inspect occasional test failure

- README.md
Kola's QEMU NAT setup does not work with firewalld.
Document that the user has to stop firewalld for QEMU tests.
> README.md: disable firewalld

- CHANGELOG.md
- cmd/kola/options.go
- platform/api/azure/api.go
- platform/api/azure/instance.go
- platform/api/azure/network.go
- platform/api/azure/options.go
- platform/machine/azure/cluster.go
- platform/machine/azure/flight.go
Add kola support for creating instances in an existing virtual network/subnet, and addressing them using private IP addresses. This assumes that we are either also located in the specified virtual network or can otherwise access it via VPN.
The `--azure-use-private-ips` option only makes sense when used together with the `--azure-vnet-subnet-name`, as otherwise kola creates the vnet and it won't be peered or have a VPN configured.
```
./bin/kola spawn --platform azure --verbose --azure-location <location> --azure-publisher kinvolk --azure-offer flatcar-container-linux-free  --azure-sku alpha --azure-use-private-ips=true --azure-vnet-subnet-name <vnet-name>/<subnet-name>
```
Ran the command from the "how-to-use" section.
> azure private networking

- kola/tests/ignition/oem.go
If the mount of the specified filesystem in Ignition is not correct,
we don't see the file written to the right disk.
Add a check that the correct file got written to.
Should fail with current ignition v3 wip until the bootengine changes are in.
It passed on [main](http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/3754/console).
As expected, it fails on the [v3 wip](http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/3755/console) without bootengine fixes:
```
Error: "cluster.go:130: \"grep -m 1 '^set linux_append=\\\"flatcar.autologin\\\"$' /usr/share/oem/grub.cfg\" failed: output , status Process exited with status 1"
```
> kola/tests/ignition/oem: Check for written file contents

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
- kola/tests/kubeadm/templates.go
- kola/tests/misc/cgroup1.go
Add test illustrating switching to cgroupv1 with no reboot.
Run test with this PR: https://github.com/flatcar-linux/coreos-overlay/pull/1666
CI running
> kola/tests: Add test for runtime switching to cgroupv1

- Jenkinsfile
Artifacts take space and we only use the latest artifacts when running tests so there is
no need for us to store more than the last 3.
> Jenkinsfile: keep artifacts from 3 latest builds

- Jenkinsfile
Now that we keep only the 3 latest build aritfacts it is perfectly fine
to enable artifact archiving for all branch/PR builds.
This will mean people no longer need to manually trigger a rebuild to test mantle changes.
> Jenkinsfile: flip default for archive artifacts to "true"

- platform/api/equinixmetal/api.go
On EM disk names are not stable and may change across reboots. This is
generally not a problem, but since we started reusing machines, it is
much more likely that there will be a leftover flatcar installation on
one disk and we are now installing to the second. This messes with some
tests because partitions from both disks may be mixed up when mounting
by label. Fix this by wiping the partition tables from disks on
reinstallation.
This should resolve a flake we've seen with cl.ignition.oem.regular, and others where "expected /dev/sda found /dev/sdb" show up.
> platform/api/equinixmetal: wipe disks before installing

- platform/api/equinixmetal/api.go
- platform/api/equinixmetal: fix disk wipe
The "disk" variable got substituted as argument for bash from the unit
instead of inside bash as shell variable.
Use escaping to prevent env var substitution inside the unit.
- platform/api/equinixmetal: disable LVM volumes before wiping the disks
The autodetection of LVM volumes can happen now that we recycle
baremetal instances through a PXE install. For the wipe to work and the
flatcar-install free disk detection we need to disable any LVM volume
first.
- platform/api/equinixmetal: delete any /dev/XdX devices
We don't want to only wipe the partitions but the full device.
Also, we have to look for vda, sdb, and xvda.
none except that the quoting is now right
> platform/api/equinixmetal: fix disk wipe

- platform/api/azure/instance.go
bpf.execsnoop times out frequently on Azure, it also takes longer than on other
platforms. Looking deeper suggests that slow disk performance may be the cause.
Switch to premium SSD for disk storage to improve disk performance and reduce
test flakiness.
> platform/azure: switch to PremiumSSD for OS disk

- CHANGELOG.md
- kola/tests/docker/docker.go
- kola/tests/etcd/discovery.go
- kola/tests/flannel/flannel.go
- kola/tests/ignition/security.go
- kola/tests/ignition/systemd.go
- kola/tests/kubeadm/kubeadm.go
- kola/tests/locksmith/locksmith.go
- kola/tests/misc/network.go
- kola/tests/misc/nfs.go
- kola/tests/misc/verity.go
- kola/tests/systemd/journald.go
- kola/tests/torcx/torcx.go
- platform/machine/unprivqemu/cluster.go
- platform/machine/unprivqemu/flight.go
- platform/machine/unprivqemu/machine.go
The "qemu" platform has the ability for VMs to connect to each other
but the "qemu-unpriv" platform lacked it, and thus would skip many
tests.
Make the qemu-unpriv platform a viable mode for running kola tests
by adding a private network. This private network only works through
static or link-local IPv4 addresses (IPv6 would work though) and it
seems that static addresses make things easier, thus they were chosen.
Yet since the required setup can't be done in the initramfs, those
tests that require initramfs private network access have to be skipped.
The tests which now can run got marked so and those that didn't work
before either but were forgotten to be excluded are now marked to be
excluded. Somehow Docker containers can't yet reach the other VMs and
the kubeadm tests have network …
> Add private network support to qemu-unpriv platform

- kola/tests/misc/files.go
The test execution races against the OEM GCE services, which unpack a container
at /var/lib/flatcar-oem-gce. This folder contains sticky and suid/sgid files,
which cause the tests to fail a lot of the time on GCE. Add
/var/lib/flatcar-oem-gce to the ignore list for relevant tests.
Going to test this in CI.
> kola/tests/misc: ignore /var/lib/flatcar-oem-gce in some tests

- kola/tests/misc/grub.go
The mask clause in coreos-cloudinit was masking the unit and then
telling systemd to reload. With that, systemd noticed that update
engine is masked and killed it, but for some reason marked it as
failed.
Current approach is to have a unit that conflicts with update engine
and masks it. That way, systemd should stop update engine without
marking it as failed and then mask it.
CI passed: http://localhost:9091/job/os/job/kola/job/qemu/3993/
> kola/tests/misc/grub.go: Try to fix grubnop test

- kola/tests/ignition/units.go
Ignition 3 spec is available starting from 3185.
<hr>
no changelog.
> test/ignition: restrict test to a MinVersion

- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-cilium-script.sh
Cilium outputs unicode characters to console even when the locale does not
allow it. Iconv can convert the output to valid ascii (replacing characters with '?').
Validated that this works by writing a small java application that directly calls
org.tap4j.parser.Tap13Parser.parseFile.
> kola/tests/kubeadm: transform cilium output to valid ascii

- kola/tests/kubeadm/templates.go
with afterburn update, a new field appears for EquinixMetal:
* `AFTERBURN_PACKET_IPV4_PRIVATE_GATEWAY_0`
This one was caught by the grep and `ipv4` value was composed of two
values:
* `AFTERBURN_PACKET_IPV4_PRIVATE_0`
* `AFTERBURN_PACKET_IPV4_PRIVATE_GATEWAY_0`
<hr>
Tested in there: https://github.com/flatcar-linux/coreos-overlay/pull/1769
> kubeadm/template: update ipv4 fetching from metadata

- platform/api/aws/ec2.go
To prevent the command for failing when an instance is stuck in pending state as here:
Couldn't gc: IncorrectInstanceState: Instance 'i-08333eba1b58744ba' cannot be stopped as it has never reached the 'running' state.
> platform/api/aws/ec2: don't abort on errors from StopInstance

- CHANGELOG.md
- kola/tests/ignition/luks.go
Ignition will set up a key-file based LUKS2 volume on a secondary disk
added to the instance.
<hr>
To be tested with: https://github.com/flatcar-linux/coreos-overlay/pull/1760 - tested here: http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/4005/
> kola/tests/ignition: add luks test

- kola/tests/ignition/kernel.go
The Ignition kargs test hits mantle's provisioning timeout due to the
additional reboot.
Since we don't really need this test to run on Equinix Metal since
running it on QEMU is equally good, we can skip it.
> kola: skip Ignition kargs test on Equinix Metal

- .dockerignore
- .github/workflows/docker.yml
- Dockerfile
A container image addresses the needs of running arm64 kola tests
without QEMU emulation but with KVM on arm64 hardware because there is
no native Flatcar SDK for arm64 yet, and it also allows us to have a
single place that provides a particular version of the mantle binaries
that is more lightweight than the full SDK where rebuilding the ebuild
package is currently needed.
The container image is published for the main branch but uses the git
SHA commit ID as image tag which should be updated in the "scripts"
repository.
There is no garbage collection yet to remove images created by PR
events.
To be used from the scripts repo in the ci-automation pipeline
For this PR an image `mantle:pr-323` was built. Checked that it gets updated on force push.
In https://github.com/pothos/mantle a …
> .github: Publish mantle container image

- kola/tests/misc/gcp.go
Add testcase for oem-gce.service on GCP. This test case is currently failing but will pass once https://github.com/flatcar-linux/coreos-overlay/pull/1813 is merged.
> kola/tests/misc: add testcase for oem-gce service running on GCP

- Dockerfile
- kola/harness.go
The logic to find the kolet binaries besides the kola binary only
worked when a relative or absolute path was used to invoke the kola
binary (argument 0).
Support running kola by finding it in the PATH where "kola" would be
the value of argument 0.
local test:
`PATH=$PATH:$HOME/kinvolk/mantle/bin kola run -d --platform=qemu-unpriv --qemu-image=/var/tmp/flatcar_production_image.bin cl.basic`
works now, didn't work before
> kola: find dir of executable if started as "kola"

- kola/tests/systemd/sysext.go
The test adds a basic sysext directory and checks that it gets loaded
and that the OEM partition mount stays present.
in https://github.com/flatcar-linux/coreos-overlay/pull/1820
> kola: add simple systemd sysext test

- Dockerfile
While ore can be used to create a GCE image, it assumes the image file
already is in a GCS bucket.
Add gsutil to the mantle container image to upload an image file to GCS
for consumption by ore.
Done [here](http://192.168.42.7:8080/job/container/job/test/246/console)
> Dockerfile: add gsutil for image upload

- CHANGELOG.md
- kola/tests/ignition/execution.go
In this PR, we add a new test to ensure `networkd` Ignition from spec 2.x is correctly translated to `files` from spec 3.x and applied correctly.
This has been tested with current stable (where `networkd` is still supported) and with https://github.com/flatcar-linux/coreos-overlay/pull/1910
Related to: https://github.com/flatcar-linux/Flatcar/issues/741
:warning: this should be merged _after_ the coreos-overlay's PR merged, backported to alpha/beta and released - otherwise test will fail (except on stable where we still on ignition 2.x so `networkd` is still supported)
> test/ignition: add `networkd` translation test

- CHANGELOG.md
- kola/tests/misc/falco.go
This tests uses the master ref of falcosecurity/falco-driver-loader, but can soon be moved to 0.33.0 once that is released. Selinux needs to be disabled because it blocks insmod from within the container.
Test succeeded: http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/553/
> kola: add test that checks that falco module can be built and loaded

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
In this PR, we remove the tests for Kubernetes 1.21.10 and we provide a new test for Kubernetes 1.24.1.
In progress: http://jenkins.infra.kinvolk.io:8080/job/os/job/manifest/5816/cldsv/
Still need to decide if we want to exclude kubernetes 1.24.1 from being tested on version != from next major.
> kola/test: add kubernetes 1.24.1

- CHANGELOG.md
- README.md
- cmd/kola/options.go
- platform/api/equinixmetal/api.go
- platform/api/equinixmetal/storage/gcs/gcs.go
- platform/api/equinixmetal/storage/sshstorage/sshstorage.go
- platform/api/equinixmetal/storage/storage.go
- platform/machine/equinixmetal/flight.go
In this PR, we abstract the temporary storage used by Equinix Metal tests and we bring the possibility to implement another ones (like SSH).
Related to: https://github.com/flatcar-linux/Flatcar/issues/720
```bash
./kola run --platform=equinixmetal ... --equinixmetal-storage-url="ssh+https://my-server"
``` 
(Voluntary obfuscated the server name) 
```
=== RUN   bpf.execsnoop
2022-06-24T09:09:18Z platform/api/equinixmetal/storage/remote: mantle-tormath1-k124-33001fe726-02888b3dd2.ign uploaded to /home/core/content/mantle-tormath1-k124-33001fe726-02888b3dd2.ign
2022-06-24T09:09:18Z platform/api/equinixmetal: user-data available at http://my-server/mantle-tormath1-k124-33001fe726-02888b3dd2.ign
2022-06-24T09:09:18Z platform/api/equinixmetal/storage/remote: …
```
> api/equinixmetal: do not exclusively rely on Google Cloud Storage

- kola/tests/misc/falco.go
The cl.misc.falco test currently fails for arm64 due to issues with the falco container image.
Disable the test.
> kola/tests/falco: disable test case for arm64

- kola/tests/kubeadm/kubeadm.go
K8s 1.24 didn't work out of the box and we had to enable containerd
and some kernel modules. This is now backported to all channels and
we should make sure that K8s 1.24 works on all channels.
None, either we do it now or merge as is and we let the nightly test it and if we see problems, fix them until the test works.
> kola/tests/kubeadm: Test K8s 1.24 with LTS, Stable, and Beta

- CHANGELOG.md
- cmd/plume/prune.go
- go.mod
- go.sum
- platform/api/aws/images.go
- vendor/github.com/aws/aws-sdk-go/aws/config.go
- vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
- vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go
- vendor/github.com/aws/aws-sdk-go/aws/request/request.go
- vendor/github.com/aws/aws-sdk-go/aws/request/retryer.go
- vendor/github.com/aws/aws-sdk-go/aws/version.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/transport.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/eventstream/eventstreamapi/transport_go1.17.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/rest/build.go
- vendor/github.com/aws/aws-sdk-go/private/protocol/rest/unmarshal.go
- vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go
- vendor/github.com/aws/aws-sdk-go/service/iam/api.go
- vendor/github.com/aws/aws-sdk-go/service/s3/api.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3iface/interface.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go
- vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload_input.go
- vendor/github.com/aws/aws-sdk-go/service/sts/api.go
- vendor/modules.txt
* support keeping N most recently created images when deleting
* support "soft-deleting" images (removing launchpermissions) for configurable time before permanently deleting
* support checking "lastlaunchtime" when image is being removed
* display statistics on image removal
* update aws go sdk
```
./bin/plume prune --check-last-launched --dry-run --channel edge -v  --keep-last 2 --days 365 --days-soft-deleted 30
```
Tested with dry-run only, would run on "edge" channel first.
> plume prune enhancement

- kola/tests/coretest/core.go
Extend TestSymlinkResolvConf to actually read the symlink and compare to the expected value.
`./bin/kola run cl.basic`
Current nightly run (fails correctly): http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/850/console
Branch with fix (succeeds): http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/851/console
> kola/tests: test resolv.conf symlink more thoroughly

- CHANGELOG.md
- kola/tests/misc/network.go
simple setup to test IP is assigned as expected.
<hr>
To be tested with: https://github.com/flatcar-linux/coreos-overlay/pull/2061 - currently it's failing but it works when adding the following section:
```yml
storage:
files:
- path: /etc/systemd/network/zz-default.network.d/wg.conf
contents:
inline: |
[Match]
Type=!wireguard
```
as suggested in the `::coreos-overlay` PR.
> test/networkd: add wireguard setup

- CHANGELOG.md
- cmd/kola/options.go
- network/jump.go
- platform/api/openstack/api.go
- platform/machine/openstack/flight.go
- platform/machine/openstack/machine.go
When spawning instance in OpenStack, VMs need to attach an interface with a public IP in order to SSH into it. With this change, we can now SSH proxy jump into the `devstack` host (Openstack dev environment)  into the VM deployed in the public network.
This reduce the dependency to floating IPs.
Related to: https://github.com/flatcar-linux/Flatcar/issues/785
Tests:
```
sudo ./bin/kola run --openstack-network public --openstack-domain default --platform openstack --openstack-flavor ds1G --openstack-user core --openstack-host 147.28... --openstack-keyfile ./id_rsa --openstack-image flatcar-stable --openstack-config-file ./openstack.json bpf.execsnoop
```
> openstack: run test with only 1 public IP

- .github/workflows/go.yml
- network/jump.go
- platform/machine/openstack/flight.go
this avoid to create a new connection for each run, we just create one
shared SSH connection for one flight instance.
<hr>
Tried with `--parallel 2 kubeadm.v1.23.4.flannel.base kubeadm.v1.23.4.calico.base`
> network: create one connection to the jump host

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
The version is prefixed with the v character, so not sure if this
check ever worked before - the test was still being run for LTS 2011,
which has version 2605, so lower than 3033.
> kola/tests/kubeadm: Fix version check

- .github/workflows/sync-calico-version.yml
Link that we have used so far to download the Tigera Operator manifest
is now dead. The documentation suggests using a versioned link, so to
avoid using the old version, add a github action to keep us
up-to-date.
Tested on my own fork:
- action run: https://github.com/krnowak/mantle/actions/runs/2888274057
- created PR: https://github.com/krnowak/mantle/pull/1
> github: Add action for syncing calico version

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
This PR is an attempt to extend kubeadm coverage by adding extra tests to test specific points for a CNI.
One test case has been added to cover the following use-case: https://github.com/flatcar-linux/Flatcar/issues/626 with IPSec encryption.
* the cluster is kept to avoid increasing overall time execution
* `kubeadm.v1.23.0.cilium.base`
> kubeadm: extend CNI tests

- .github/workflows/sync-calico-version.yml
- CHANGELOG.md
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
~I'll need to update the github action to mention in the created PR that these templates should be manually compared with the original versions.~
There seemed to be a race between using one manifest file to create CRDs and afterwards applying another manifest file that was using those CRDs. Sometimes the CRDs were not established, so the resources of that type could not be used. Use `kubectl wait` to make sure that those CRDs are ready.
While at it, sync our modified custom-resources.yaml manifest with the upstream and add a note about it to the github action. The note looks like in this PR: https://github.com/krnowak/mantle/pull/2.
Test run: http://jenkins.infra.kinvolk.io:8080/job/container/job/test/1988/console (note the `customresourcedefinition.apiextensions.k8s.io/installations.opera …
> kola: More calico fixes

- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
- kola/tests/kubeadm/testdata/master-cilium-script.sh
- kola/tests/kubeadm/testdata/master-flannel-script.sh
It's available since k8s 1.15, so we can safely use it and avoid
deprecation warnings.
Not sure if it's worthy of a changelog entry.
> kola/tests/kubeadm: Bump kubeadm config API version

- CHANGELOG.md
- platform/api/equinixmetal/api.go
`s3.xlarge.x86` has some nvme disks attached, which have the smallest size in bytes from all the available disks. Since we are passing the `-s` flag to `flatcar-install` (so the scripts find the smallest disk to install flatcar), they get picked. For some reason, they can't be booted. The nvme devices have major 259, whereas other disks - 8.
I had two ways of fixing the issue - either exclude 259, or include only 8. Went with the former.
During trying to find the fix I did some small cleanup.
The commit messages still need to be rewritten.
I also had a commit that drops fiddling with AlwaysPXE flag, and uses reinstall action instead. This might be something to consider, but it's certainly slower, since all the disks seem to be zeroed. So in case of `s3.xlarge.x86` instance, the …
> equinixmetal: Exclude weird devices from flatcar installation

- CHANGELOG.md
- kola/tests/kubeadm/checksums.sh
- kola/tests/kubeadm/kubeadm.go
Also comes with a script that get the checksums.
> Add k8s 1.25 to kubeadm tests

- kola/tests/misc/network.go
<hr>
It has been raised on Matrix that wireguard does not seem working on VMWare.
> test/network: add vmware to wireguard test

- CHANGELOG.md
- cmd/kola/bootchart.go
- cmd/kola/options.go
- cmd/kola/spawn.go
- cmd/kola/updatepayload.go
- kola/harness.go
- platform/api/equinixmetal/api.go
- platform/journal.go
- platform/platform.go
This could be used by vendor tests to increase timeouts for running tests on big EM instances
> api/equinixmetal: Make timeouts configurable

- kola/tests/kubeadm/kubeadm.go
But try to make it general, so the information about the test are in a
single place.
Not adding the changelog - it's a fix for a recent feature.
> kola/tests/kubeadm: Skip 1.25 on old versions too

- cmd/ore/aws/delete.go
- cmd/ore/aws/upload.go
- cmd/plume/prerelease.go
- cmd/plume/prune.go
- platform/api/aws/images.go
We have a job that runs `plume prune` on all channels to cleanup older ec2 images. This has not worked yet, because of two issues (second one uncovered after fixing first one):
* `plume prune` uses the current regions auth token when iterating, which does results in an error from the S3 object deletion which is tied to a single region. Handle region switching to delete the object from the bucket if necessary.
* for old releases (eg. alpha-2121.0.0), the snapshot search finds two matching snapshots (one for hvm, one for non-hvm). This causes the removal to be aborted with an error. Handle this by deleting both snapshots, since the function can handle failure to delete snapshots.
```
bin/plume prune --days 365 --keep-last 2 --days-soft-deleted 21 --check-last-launched --days-last-launched …
```
> AWS prune all snapshots

- CHANGELOG.md
- cmd/plume/prerelease.go
- cmd/plume/release.go
We use the us-east-1 AMIs ID to programmatically update the AWS Marketplace offer.
CI (or human) must provide the product-id and the access role ARN to update the offer. See also the documentation for the `ore aws update-offer` subcommand.
<hr>
Not tested - we can try it during the next release. It's designed to not fail if the update of the offer fails.
Related to: https://github.com/flatcar-linux/Flatcar/issues/838
Update of the offer itself: https://github.com/flatcar-linux/mantle/pull/282
> plume/release: publish on the AWS Marketplace

- README.md
- kola/README.md
- platforms.md
- runner-readme.md
Also, cork is deprecated, so point to the correct location for documentation about working with SDK.
This is just fixing documentation files, so no code changes here.
> docs: Replace flatcar-linux with flatcar

- CHANGELOG.md
<hr>
A new release has been done: https://github.com/flatcar/mantle/releases/tag/v0.19.0 from the commit: https://github.com/flatcar/mantle/commit/3668425d20dac9f0471fb94b9f36d00ba822f68e to avoid introducing non-tested features on the `plume` command.
In this PR, we just update the CHANGELOG to add the `0.19.0` section.
> changelog: cut a new release

- Dockerfile
The cloudformation update is done with the aws tool as of now, and we need it in the build pipeline https://github.com/flatcar/scripts/pull/475 until we move this logic into plume.
Checked that https://github.com/flatcar/flatcar-build-scripts/blob/master/update-cloudformation-template can run in the container
> Dockerfile: Add aws CLI tool

- cmd/plume/prerelease.go
- cmd/plume/release.go
it happens that the same AMI can be published for multiple offers (like stable / stable-pro)
```
--product-ids p1,p2,...pN
```
> plume: support multiple product IDs for one AWS release

- cmd/plume/release.go
The web URL of the GCE image (like: http://bincache.flatcar-linux.net/.../flatcar_production_gce.tar.gz) can't be directly used to create the image on GCP.
It's required to temporary upload the image on GCS to get a "https://storage.googleapis.com" link which is __required__ by the API to create an image on GCP.
> plume/release: upload GCE image on GCS

- platform/api/openstack/api.go
the image usually takes a few second to be unpacked on the Openstack instance.
It can leads to CI error if the image used to run the test it not yet fully active.
> openstack/api: wait for image to be active

- kola/tests/devcontainer/devcontainer.go
Older images may not have lbzcat, so fall back to bzcat.
> kola/tests/devcontainer: Fallback to bzcat

- CHANGELOG.md
- kola/tests/coretest/core.go
The coreos.com address seems to be no more:
```
$ docker run ghcr.io/kinvolk/busybox ping -c4 coreos.com
ping: bad address 'coreos.com'
```
This is to fix `cl.internet/DockerPing` test failures that started to happen today:
- http://jenkins.infra.kinvolk.io:8080/job/container/job/test/3380/consoleText
- http://jenkins.infra.kinvolk.io:8080/job/container/job/test/3379/consoleText
- http://jenkins.infra.kinvolk.io:8080/job/container/job/test/3374/consoleText
- http://jenkins.infra.kinvolk.io:8080/job/container/job/test/3375/consoleText
> kola: Ping flatcar.org instead of coreos.com

- cmd/plume/containerlinux.go
- cmd/plume/prerelease.go
Recently we ran into sporadic corruption issues for AWS EC2 AMIs. We use the streamOptimized VMDK format and it seems to cause problems at the AWS side, regardless if created by qemu-img or vmdk-convert. Switch to using the plain AMI images for uploading as workaround.
When merged and the scripts repo has new mantle ref update PRs, merge them and retag the releases.
Will be tested as part of the release.
> plume: Use plain AMI image for uploads

- CHANGELOG.md
- kola/tests/kubeadm/kubeadm.go
this is EOL since the 28th of Oct.
<hr>
```
kola run --platform openstack ... kubeadm.v1.23.4.cilium.cgroupv1.base kubeadm.v1.23.4.flannel.cgroupv1.base
1..3
ok - kubeadm.v1.23.4.calico.cgroupv1.base
ok - kubeadm.v1.23.4.flannel.cgroupv1.base
ok - kubeadm.v1.23.4.cilium.cgroupv1.base
```
> tests/kubeadm: drop k8s 1.22.7

- kola/tests/ignition/empty.go
OpenStack should now support SSH keys provisioning from the OpenStack metadata server.
<hr>
I think it's ok to exclude current LTS from this test, because we still have the `cl.ignition.v1.noop` test and v1 is translated to v3, so this behavior will still be tested on the current LTS.
:warning: Do not merge this until https://github.com/flatcar/coreos-overlay/pull/2246 has been backported to all channels. (except LTS) :heavy_check_mark:
> tests/ignition: add empty Ignition config test for openstack

- kola/harness.go
- kola/register/register.go
- kola/tests/bpf/local-gadget.go
- kola/tests/docker/torcx_manifest_pkgs.go
- kola/tests/ignition/resource.go
- kola/tests/ignition/security.go
- kola/tests/kubeadm/kubeadm.go
- platform/api/esx/api.go
In this PR, we add the `ip` kernel argument following this pattern[^1]:
```
ip=<client-IP>:[<peer>]:<gateway-IP>:<netmask>:<client_hostname>:<interface>:{none|off|dhcp|on|any|dhcp6|auto6|ibft}[:[<dns1>][:<dns2>]] 
```
and we remove `esx` from excluded platforms for network reasons.
<hr>
Related to: https://github.com/flatcar-linux/Flatcar/issues/717
I'm not sure it takes a changelog entry
EDIT: don't merge this before getting the feature in stable - otherwise we'll prevent the impacted tests to run
[^1]: https://mirrors.edge.kernel.org/pub/linux/utils/boot/dracut/dracut.html#_network
> esx: support initramfs network configuration

- kola/harness.go
`SkipFunc` is called from `FilterTests` and `FilterTests` is called twice: before and after spining-up a test instance to get the version.
We need to assert to be in the second case, where the version is actually defined - otherwise it simply ignores the test from the start.
Notified from the VMWare kubeadm that did not run on main nightly.
> kola/harness: run `SkipFunc` when version is available

- kola/tests/systemd/sysext.go
This tests that users are able to supply a custom Docker version as sysext. It uses create_docker_sysext.sh which is documented in https://www.flatcar.org/docs/latest/provisioning/sysext/
Replace branch checkout by git commit ID when https://github.com/flatcar/sysext-bakery/pull/6 is merged
`sudo ./kola run -d -k --keys --key ~/.ssh/id_rsa.pub  --board=amd64-usr --parallel=1 --platform=qemu  --qemu-image=flatcar_production_image.bin  --qemu-skip-mangle systemd.sysext.custom-docker`
> kola: Add custom Docker sysext test

- Dockerfile
While the mantle container has plume/ore for publishing cloud images, not all actions are implemented in plume or ore. We already have the awscli for some publishing steps but the "az" tool from azure-cli was missing and is useful for image gallery publishing.
From https://github.com/flatcar/scripts/blob/380f9723290932e04f3a057a1a0cf04e7b56a93b/ci-automation/release.sh#L150
`docker run --rm -it ghcr.io/flatcar/mantle:pr-399` and then `az`
> Dockerfile: Add azure-cli for image gallery publishing

- .github/workflows/docker.yml
- .github/workflows/go.yml
- .github/workflows/sync-calico-version.yml
- avoid warnings about using deprecated stuff
- take golang version from go.mod instead of hardcoding yet another golang version in the job
- run sync calico version once a week instead of twice a day
No need for the changelog entry.
> Update github actions

- CHANGELOG.md
- kola/tests/misc/ntp.go
Since systemd v251, output messages of `systemd-timesyncd` started having a different format, not `Initial synchronization to time server`, but `Contacted time server`.
As a result, the `linux.ntp` test failed even when systemd-timesyncd ran without any issue.
```
ntp.go:80: unexpected systemd-timesyncd status: "systemd-timesyncd.service
Status: \"Contacted time server 10.0.0.1:123 (10.0.0.1).\"\n
Jan 03 18:43:08 localhost systemd[1]: Starting Network Time
Synchronization...\nJan 03 18:43:08 localhost systemd[1]: Started
Network Time Synchronization.\nJan 03 18:43:08 localhost
systemd-timesyncd[904]: Contacted time server 10.0.0.1:123
(10.0.0.1).\nJan 03 18:43:08 localhost systemd-timesyncd[904]: Initial
clock synchronization to Tue 2023-01-03 18:43:08.835535 UTC.
```
Add another entry …
> kola: add output message for systemd-timesyncd v251

- platform/api/azure/api.go
- platform/api/azure/instance.go
Fetch Azure marketplace plan information dynamically, so that `kola spawn` works for the Arm64 CoreVM offer.
```
./bin/kola spawn --platform=azure --azure-location eastus2 --azure-publisher kinvolk --azure-offer flatcar-container-linux-corevm --azure-sku stable --azure-size "Standard_D2pls_v5" --azure-hyper-v-generation V2 --azure-auth ... --azure-profile ...
```
> platform/azure: fetch marketplace image plan info from endpoint

- kola/harness.go
- kola/register/register.go
- kola/tests/misc/verity.go
- kola/tests/update/update.go
When testing changes with kola and the tests do not cover the changed area we either have a booting system (that passes the tests) or don't. With additional generic checks we can catch introduced errors in an automated way and the manual booting to inspect a boot failure can also be saved if kola can hint at errors. Examples are broken changes in the systemd unit setup, when services start to fail, or when the disk is corrupted (be it due to a kernel bug, broken hardware, or a cloud provider image problem).
Add more checks for the above failures. If a test provokes one of these failures, the test and the pattern will have to be marked with a flag that skips the patterns for those tests only (this is what we already do for the existing patterns).
Made a [full kola test …
> kola/harness: Add more checks for common failures

- kola/tests/misc/network.go
The combined log format uses the form
"Started systemd-networkd.service - Network Configuration." to show both the unit name and the description.
[here](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/7283/console)
> kola/tests: Also match combined systemd log format

- kola/tests/misc/files.go
The copy of the factory /etc in /usr/share/flatcar/etc may have dead
links because the relative linking assumes to be under /TOPDIR
(https://github.com/flatcar-linux/scripts/pull/264).
Ignore the folder in the check for dead links, we still check the
resulting /etc hierarchy created based on it.
Needed for the linked scripts PR
[here](http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/4055/console)
> cl.filesystem/deadlinks: ignore factory /etc in /usr/share/flatcar/etc

- kola/tests/misc/state.go
The /etc overlayfs mount is there to be able to update the lowerdir file and this only works if we have no unwanted duplicates in the upperdir (i.e., the /etc folder).
Add tests to check against upcopies caused by, e.g., systemd-tmpfiles and to check that duplicates get removed on reboot (introduced in https://github.com/flatcar/coreos-overlay/pull/2482).
Expected to pass for https://github.com/flatcar/coreos-overlay/pull/2482
[CI](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/7932/consoleFull)
and local run of `cl.overlay.cleanup`
> kola/tests: Add test for /etc overlay upcopy prevention and cleanup

- kola/tests/ignition/oem.go
The mount unit for the OEM in the initrd gets triggered at different points when doing a reboot with Ignition, and in the current Flatcar versions this leads to a failure because Ignition can't mount when something else already triggered the mount unit.
Should verify that https://github.com/flatcar/Flatcar/issues/979 is fixed and doesn't come back
Manually ran both tests for the image from https://github.com/flatcar/bootengine/pull/58
> kola/tests/ignition/oem: Cover more code paths in the initrd

- .github/workflows/mirror-calico-images.sh
- .github/workflows/mirror-stable-docker-images.yaml
- .github/workflows/mirror-to-ghcr.sh
- .github/workflows/sync-calico-version.yml
- README.md
- kola/README.md
- kola/tests/coretest/core.go
- kola/tests/docker/docker.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
- kola/tests/kubeadm/testdata/master-cilium-amd64-config.yml
- kola/tests/kubeadm/testdata/master-cilium-arm64-config.yml
- kola/tests/systemd/sysext.go
- replaced some links
- replaced kinvolk/busybox, kinvolk/nginx and kinvolk/calico with flatcar variants
- https://github.com/flatcar/scripts/pull/716 needs to go in and the actions there need to be run first
- fixed a final newline issue with kubeadm templates
> Replace kinvolk links and docker images with flatcar ones, sync docker images

- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
This reverts commit f3be8d0c0a77ea0dcfe25a7f02b796a29309274f, to fix regressions in CI tests of calico.
> Revert "Update calico to v3.25.1"

- .github/workflows/mirror-stable-docker-images.yaml
- .github/workflows/sync-calico-version.yml
I thought that scheduled action runs will use default values for the specified inputs, but in reality all the inputs are null for such runs. This is kinda lame, as we need to specify the default value in two places now.
> .github: Fix usage of inputs in scheduled action runs

- kola/tests/kubeadm/kubeadm.go
Latest releases, v1.26.5, v1.25.10, and v1.24.14 started being not published tothe old registry `k8s.gcr.io`, while previous versions are still in the old registry.
As a result, an old kubeadm version like v1.24.1 cannot run, because it tries to fetch k8s manifests from the old registry.
```
cluster.go:117: failed to pull image "k8s.gcr.io/kube-apiserver:v1.24.14"
```
To fix that, update each K8s binaries to the latest updates, v1.26.5, v1.25.10 and v1.24.14.
Locally tested
> kola/kubeadm: update k8s versions to the latest

- CHANGELOG.md
- kola/harness.go
- kola/tests/devcontainer/devcontainer.go
- kola/tests/ignition/oem.go
- kola/tests/systemd/sysext.go
- kola/tests/update/update.go
- kola/tests/util/devcontainer.go
- kola/tests/util/template.go
- platform/api/equinixmetal/api.go
This adds a new sysext test that builds and activates an OEM sysext image. It also prepares the tests for the move of the OEM partition mountpoint move from `/usr/share/oem` to `/oem`. It required duplicating some of the tests, so the variants with `/usr/share/oem` will be run for Flatcar versions lower than 3603.0.0 (so new alpha release being 3602.0.0 will run the `/usr/share/oem` variants), and the variants with `/oem` will be run for Flatcar 3603.0.0 or newer.
> another sysext test + /usr/share/oem -> /oem

- CHANGELOG.md
- kola/tests/systemd/sysext.go
We will move docker packages from app-emulation to app-containers to match what Gentoo did with their docker packages. Since the tests will be also running on older versions of Flatcar, keep searching for docker package in old category too.
> kola/tests/systemd: Try also different category for docker package

- kola/tests/misc/cloudinit.go
- platform/conf/conf.go
- platform/conf/multipart.go
The new multipart mime support that is currently being proposed against coreos-cloudinit needs to be tested. This PR adds the needed tests.
These tests will validate that we properly parse the multipart mime user-data and all parts are run correctly.
> Add tests for multipart mime in coreos-cloudinit

- CHANGELOG.md
- kola/tests/misc/nvidia.go
> Add tests for the NVIDIA GPU tests

- Dockerfile
Now Debian 12 is released and the Go 1.20 image uses it as base.
> Dockerfile: Update base image

- kola/tests/update/update.go
- kola/tests/util/update.go
The A/B updated OEM systemd-sysext image gets activated when both /usr partitions have updated to a version that requires a sysext image. The old OEM contents get cleaned in this migration that happens on the boot after the final update.
Test this migration and update logic by starting from an old image that isn't migrated, and emulate an OEM setup that requires an OEM sysext image now. The update first happens with the inbuilt Omaha kolet server which uses the fallback logic but then flatcar-update is used for the second update to supply the OEM payload directly.
See scripts PR: https://github.com/flatcar/scripts/pull/1016
Manual and on [Jenkins](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/13949/console)
> kola: Add new OEM sysext update and migration test

- kola/tests/update/update.go
Previously the regular image-key-signed build artifact was used but now we can use the dey-key-signed update payload.
See https://github.com/flatcar/bootengine/pull/71
> kola: Adjust comment of fallback download test to use the payload name

- kola/tests/util/update.go
The use of findmnt, and possibly falling back to dmsetup info is fragile and does not work well with, e.g., btrfs.
Use the rootdev tool from the seismograph repo to resolve the backing device.
For https://github.com/flatcar/scripts/pull/1170
See linked PR
> GetUsrDeviceNode: Use rootdev tool to resolve backing blockdev

- CHANGELOG.md
- kola/tests/misc/state.go
Remove directory `/etc/samba` with `rm -rf`, to be able to deal with cases of `/etc/samba` not being created at all, like samba >= 4.18, which results in `rm -r` failing.
Adjust comments as well.
See also https://github.com/flatcar/scripts/pull/1191.
> kola: remove /etc/samba with an -f option

- kola/tests/update/update.go
We currently have no way to switch the update pub key in the initrd to be a dev key (or vice versa). Thus the test cl.sysext.fallbackdownload failed because based on the key either the update server or bincache is tried.
Skip cl.sysext.fallbackdownload for release builds at least temporarily. Later we might use a kernel cmdline setting or similar to switch the key to a dev key.
Locally, once for the nightly (dev build), once for the new Alpha (release build)
> kola: Skip cl.sysext.fallbackdownload for release builds

- kola/tests/misc/nvidia.go
The nvidia.service has been change to `oneshot` and sets `RemainAfterExit=true` which keeps the service active after it exits.
> kola/nvidia: Change the nvidia retry clause

- kola/harness.go
- kola/register/register.go
- kola/tests/ignition/empty.go
- kola/tests/locksmith/locksmith.go
- kola/tests/misc/omaha.go
- platform/cluster.go
- platform/conf/conf.go
- platform/platform.go
This might have been an oversight: for release tests we used the public Nebraska server. This was already disabled for FCOS but not for the original CoreOS/Flatcar CL.
Disable the public update server by default. The update tests overwrite it with their specific setting. In case a future test needs the default the usual test flag escape hatch in the form of NoDisableUpdates is added.
[here](http://jenkins.infra.kinvolk.io:8080/job/container/job/test_dispatcher/2526/cldsv/)
> kola: Disable the public update server by default

- kola/README.md
- kola/cluster/cluster.go
- kola/registry/registry.go
- kola/tests/bpf/bpf.go
- kola/tests/docker/enable_docker.go
- kola/tests/docker/torcx_manifest_pkgs.go
- kola/tests/sysext/disable_containerd.go
- kola/tests/sysext/disable_docker.go
- kola/tests/sysext/sysext.go
- kola/tests/systemd/journald.go
This PR prepares kola for torcx deprecation. It is a prerequisite for https://github.com/flatcar/scripts/pull/1216 . 
- A new "sysext" test module has been introduced; the existing `sysext.go` has been moved there from the `systemd` module.
- two additional tests for disabling the docker and containerd sysexts have been added there, too.
- The "torcx" test module has been removed entirely - it contained a single test (explicitly enabling docker) which needed to be extended to cover sysext docker. That test has been moved to `docker/enable_docker.go`.
- Torcx tests are made to run conditionally and will run only for major version below a certain threshold (currently up to version 3745 but this will need to be updated depending on when https://github.com/flatcar/scripts/pull/1216 gets …
> Kola: update to handle torcx deprecation / docker and containerd sysext

- kola/tests/docker/enable_docker.go
- kola/tests/docker/torcx_manifest_pkgs.go
- kola/tests/sysext/disable_containerd.go
- kola/tests/sysext/disable_docker.go
- kola/tests/sysext/sysext.go
I forgot to update the Flatcar major release versions in which torcx would be deprecated before merging https://github.com/flatcar/mantle/pull/465 . This PR fixes that; it uses today's major release 3760 as cut-off point for torcx specific tests.
> kola: bump torcx deprecation major release number

- kola/tests/docker/docker.go
- kola/tests/kubeadm/kubeadm.go
- kola/tests/sysext/sysext.go
This PR contains fixes for tests to add support for testing docker version 24. Docker 24 changes a number of defaults that cause issues with tests.
Required for https://github.com/flatcar/scripts/pull/1305, part of https://github.com/flatcar/Flatcar/issues/1091.
> kola: support docker in portage stable, add support for docker 24

- kola/tests/update/update.go
This change adds an update test for instances using the docker btrfs storage driver. This storage driver was deprecated in docker release 23 and will be removed in a future release.
Docker 23 and above support backwards compatibility if BTRFS storage exists and is populated.
This test verifies that instances with btrfs storage don't break on update.
> tests/update: Add test for docker btrfs storage driver

- kola/tests/ignition/filesystem.go
This is a testcase for a regression that passes until Flatcar 3374 and fails on Flatcar 3510 (only checked stable releases).
> kola: Add test case for extra partition creation

- kola/tests/misc/state.go
For files like /etc/resolv.conf we want it to be recreated because the tmpfiles rule would do this. For a systemd bug workaround we filtered out some rules but even if we add them back, we still want to ensure that not only the file will always be recreated but that it also is not frozen as upcopy because we prefer the overlay lowerdir as source for updates.
Extend the /etc overlayfs test to ensure recreation of the file and to check against upcopies.
Will pass for fixed releases.
```
sudo ./kola run -d -k --keys --key ~/.ssh/id_rsa.pub --platform=qemu  --qemu-image /var/tmp/flatcar_production_image.bin.whiteouts cl.overlay.cleanup
```
passed (and fails for current releases)
> kola: Extend test to cover recreation of files in /etc

- .github/workflows/build-push-iovisor-bcc.yaml
- kola/tests/bpf/bpf.go
* Added .github/workflows/build-push-iovisor-bcc.yaml workflow to build and push the image to ghcr.io/flatcar/bcc:latest
* Switch to the ghcr.io/flatcar/bcc:latest image instead of the quay.io/iovisor/bcc image
Until PR https://github.com/iovisor/bcc/pull/4845 is merged or the issue https://github.com/iovisor/bcc/issues/4842 is addressed, we need to use the branch with required fix to changelog and python3 modules.
> iovisor/bcc: add Docker image build/push workflow

- .github/workflows/build-push-iovisor-bcc.yaml
The upstream repository docker image build got fixed: https://github.com/iovisor/bcc/pull/4845
Tested the manual Docker image using Ubuntu dockerfile and it worked on ARM64:
```bash
git clone https://github.com/iovisor/bcc
cd bcc
docker build -f docker/Dockerfile.ubuntu
```
> bcc: use upstream iovisor/bcc repository

- Dockerfile
- kola/tests/misc/falco.go
Falco driver loader 0.37.0 or later is broken for Flatcar at the moment. The loader switched from the old bash script to a replacement implemented in falcoctl. The image is based on Alpine instead of Ubuntu and is missing a bunch of dependencies (patchelf, bash, maybe more).
> kola: Pin falco driver loader to 0.36.2

- kola/tests/misc/falco.go
The fix for Flatcar is in the falcoctl 0.7.2 release, which got picked up by the master version of falco-driver-loader.
> kola: Go back to using master version of falco driver loader

- kola/harness.go
- kola/tests/sysext/zfs.go
These tests cover multiple use cases:
- fetching the sysext from the release server
- systemd units work and datasets get mounted
- docker zfs driver works
- setting up network shares works
> Add kola tests for zfs

- test
go test -i is deprecated and has been removed. It no longer serves a purpose. See: https://github.com/golang/go/issues/41696
> Fix test script for Go >=1.20

- kola/tests/devcontainer/devcontainer.go
- kola/tests/misc/tang.go
We use Equinix Metal machines in our CI that have bonded network interfaces, which means we end up with nics with no ips. The tang setup code needs to handle this. We will also want to rework the code to provide tang in the same way as we do for etcd.
> kola/tests/tang: Ignore interfaces with no IPs

- .github/workflows/docker.yml
- kola/tests/misc/tang.go
- platform/local/cluster.go
Fix the tang test by moving the tang listener into the qemu network namespace.
Also an attempt to speed up container build so the second commit will be pushed after the first build completes.
> Fix tang test (part 2)

- kola/tests/bpf/local-gadget.go
- kola/tests/coretest/core.go
- kola/tests/ostree/basic.go
- kola/tests/ostree/unlock.go
- kola/tests/rpmostree/deployments.go
- kola/tests/update/update.go
systemd-timesyncd.service will not be the only ntp implementation enabled by default on all platforms, so the test needs to take that into account.
> fix check for systemd-timesyncd.service

- cmd/kola/options.go
- cmd/ore/aws/upload.go
- cmd/ore/gcloud/gcloud.go
- cmd/ore/gcloud/upload.go
Some image/project/bucket names still reference coreos, switch to the correct flatcar values. n1-standard-1 instances are old and slightly more expensive than t2d-standard-1 so make those the default. We have also enabled "public access restriction" on our test bucket, so to get `ore gcloud upload` to work we need to switch the default object ACL to projectPrivate.
> gce: Update default options

- kola/tests/misc/verity.go
For a particular image build the filesystem seemed to be more resistant to the corruption test, be it due to the corruption hitting other structures or some non-flushable cache covering more of the corrupted area. One can still trigger the verity panic by overwriting 100 MB instead of 10 MB.
Increase the amount of zeros written by the corruption test.
Tested with the amd64 image here https://bincache.flatcar-linux.net/images/amd64/9999.9.9+kai-remove-acbuild/flatcar_production_image.bin.bz2 which was able to avoid the direct panic on the 10 MB corruption due to caching effects.
> kola: Increase amount of disk corruption in verity test

- platform/api/azure/gallery-image-template.json
Followup for: https://github.com/flatcar/mantle/pull/517
I tested that PR with an externally created gallery, and didn't test the gallery creation itself, so I missed this detail.
Surprisingly API version 2022-08-01 does not exist for the galleries resource provider. The SDK uses 2022-01-01 even when we import 2022-08-01. Since we use an ARM template for gallery creation, we have to manually select the correct api version, otherwise gallery creation fails.
The error I get is:
> 2024-04-05T12:27:49Z ore/azure: Couldn't create gallery image: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details." Details=[{"code":"BadRequest","message":"{\r\n …
> platform/api/azure: Switch gallery API version to 2022-08-03

- cmd/kola/options.go
- platform/api/azure/api.go
- platform/api/azure/instance.go
- platform/api/azure/options.go
An alternative approach to reusing a resource group: only store VM object in the passed resource group and all other objects go in the kola managed RG. Instances already get deleted separately from rgs at the end of the run.
This is needed to support availability set that may be pinned to a specific compute resource. VMs that are part of an availability set must share a resource group with the availability set and must share a vnet.
> azure: Add support for using an external availability set and resource group

- kola/tests/misc/tpm.go
As documented in https://github.com/flatcar/flatcar-website/pull/317 we can use PCR binding in Flatcar with some limitations and workarounds. I think we should be able to get rid of the first boot PCR difference by handling the first-boot flag detection in userspace and if we can guarantee that the outcome of setting the first boot or not is the same, i.e., we would have to always measure the effective Ignition config. For the rebinding on update the best bet we have is to create a Flatcar variant with sd-boot for signed PCR policies. Anyway, these are future topics and it's already good that we can make some encryption setups work.
Tested both new tests with the image from https://github.com/flatcar/scripts/pull/1861
> kola: Add tests for encrypted root disks with TPM PCR binding

- cmd/kola/options.go
- kola/tests/misc/tpm.go
- platform/local/tpm.go
- platform/machine/qemu/cluster.go
- platform/machine/qemu/flight.go
- platform/machine/qemu/machine.go
- platform/qemu.go
So that kola spawn can support `--qemu-tpm` for testing.
> qemu: extract swtpm

- kola/tests/misc/tpm.go
- platform/local/tpm.go
The TPM directory is created under the _kola_temp folder for the VM. In total the path used for the swtpm socket was above the 108 char limit for some tests.
Shorten the affected test names to keep the socket path under the limit.
Rerun Jenkins tests with this
Tests passed for [qemu on amd64](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/21808/console) and [qemu_uefi on arm64](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/21809/console)
> kola: Shorten TPM test name to keep the socket path under the limit

- kola/tests/misc/tpm.go
- platform/local/cluster.go
- platform/local/configdrive.go
- platform/local/tpm.go
- platform/machine/qemu/cluster.go
- platform/machine/qemu/machine.go
- system/ns/exec.go
The long UNIX socket path caused problems and the workaround was to shorten the test names but a real solution is to ensure that the path is always short. This can be done by setting the current working directory for the swtpm process to the machine folder which also holds the socket and, in addition, setting the current working directory for the qemu process to the same folder. Then we can use 'tpm/socket' as path which is ensured to be below the limit of 108 characters.
Tests [passed on GitHub Actions](https://github.com/flatcar/scripts/actions/runs/8705614424?pr=1908) in this [test PR](https://github.com/flatcar/scripts/pull/1908)
> kola: Run qemu and swtpm with the machine folder as working dir

- kola/tests/misc/falco.go
The driver-loader switched to using "modern_ebpf" mode by default, but lets continue testing kmod.
> kola/tests/falco: Pass kmod to driver loader

- platform/machine/qemu/cluster.go
- platform/machine/unprivqemu/cluster.go
- platform/machine/unprivqemu/machine.go
- system/exec/exec.go
- kola: Align qemu-unpriv with qemu after new additions
The qemu-unpriv platform doesn't support as many test scenarious as the
priv. qemu platform but it is still useful for testing. When doing
changes in the qemu platform we should also do them for qemu-unpriv.
Port the last changes over to get swtpm support.
- kola: Fix path for qemu-bios argument
After changing the qemu working directory, relative qemu-bios path
arguments stopped working.
Handle relative paths by prepending kola's current working directory.
The changes from
`git diff --no-index platform/machine/qemu/ platform/machine/unprivqemu/`
show that only platform-specific options differ. As a test
`cl.tpm.root-cryptenroll` passed for `--platform=qemu` and
`--platform=qemu-unpriv` when run with …
> kola: Fix path for qemu-bios argument

- kola/tests/misc/files.go
After enabling the user dbus session, the dead link check fails because the path always contains dead links but that's expected behavior.
Fixes test failure in https://github.com/flatcar/scripts/pull/1964
Local run passes for the built image
> kola: Exclude user dbus session entries from dead symbolic links check

- CHANGELOG.md
- cmd/plume/prerelease.go
- cmd/plume/release.go
Add the support to run the pre-release and the release jobs via managed idenities 
to be merged with https://github.com/flatcar/scripts/pull/2048
> plume/azure: Add support for managed identity

- cmd/kola/options.go
- platform/api/azure/groups.go
- platform/api/azure/instance.go
- platform/api/azure/network.go
- platform/api/azure/options.go
- platform/api/azure/storage.go
Resource deletion can take a long time - switch to submitting a deletion request for resource group/VMs but don't poll on the outcome. This doesn't fail 99.9% of the time and we have automation to catch the 0.1%.
Add a parameter (azure-kola-vnet) that allows disabling public access to storage accounts and restricting access to a single vnet.
> Azure updates

- README.md
The AMD64 kola example now also requires the uefi to be set accordingly: `flatcar_production_qemu_uefi_efi_code`, fixed a small nit ~/.ssd -> ~/.ssh and made the ARM64 example be consistent parameter order wise with the AMD64.
> readme: updated the AMD64 kola example

- CHANGELOG.md
- platform/api/azure/gallery-image-template.json
I was notified of a breaking API change occurring on 2024/11/05. It did not appear necessary to update the permissions in the Terraform file.
Build Kola and deploy to Azure.
Tested by deploying Flatcar with Kola.
> azure: Update storage config following Gallery Image API change

- platform/api/azure/instance.go
- platform/machine/azure/cluster.go
Currently, see: https://github.com/flatcar/Flatcar/issues/656, Flatcar on Azure does not support the Azure Virtual Machine feature AzureVM-UserData (https://learn.microsoft.com/en-us/azure/virtual-machines/user-data) enabled when the userdata is in cloud-init (cloud-config) format. It requires the Azure Virtual Machine feature called AzureVM-CustomData (https://learn.microsoft.com/en-us/azure/virtual-machines/custom-data) to be enabled. Yes, I know, confusing.
This change fixes the flakiness in the `cl.cloudinit.basic` Mantle test, which sometimes was run with AzureVMUserData enabled.
Patch made by @jepio.
Fixes: https://github.com/flatcar/Flatcar/issues/1505
> azure: enable CustomData if the userdata has cloud-init format

- README.md
- kola/tests/crio/crio.go
- kola/tests/docker/docker.go
- kola/tests/podman/podman.go
OpenBSD netcat has no long flags and has no idle timeout flag, so these need to be replaced with short flags and using a timeout utility, respectively.
> kola/tests: Replace nmap's ncat with openbsd ncat

- README.md
- cmd/kola/options.go
- kola/harness.go
- kola/tests/misc/falco.go
- kola/tests/sysext/zfs.go
- platform/machine/qemu/cluster.go
- platform/machine/qemu/flight.go
- platform/machine/qemu/machine.go
- platform/machine/unprivqemu/cluster.go
- platform/machine/unprivqemu/machine.go
- platform/platform.go
- platform/qemu.go
@sayanchowdhury + @jepio
* add new kola command line flags: --qemu-ovmf-vars and --enable-secureboot. --enable-secureboot will eventually be useful for other platforms as well (AWS/GCP/Azure).
* --qemu-bios has been renamed to --qemu-firmware, but --qemu-bios is kept around so that we don't break old releases if we only backport kola changes.
* ovmf vars file is copied into instance folder per test case execution
* skip falco and zfs tests when secure boot: unsigned kernel modules can't be loaded when secure boot is enabled, enforced by lockdown integrity mode.
* force boot from primary disk using `bootindex`
Tested here: http://jenkins.infra.kinvolk.io:8080/job/container/job/test_dispatcher/5120/cldsv/ with ghcr.io/flatcar/mantle:pr-554
> support testing secureboot in Qemu

- .github/workflows/build-other-docker-image.yaml
- kola/tests/packages/openiscsi.go
- kola/tests/packages/packages.go
- other-dockerfiles/targetcli-fb/Dockerfile
This PR adds a github action that can be used for building docker images based on dockerfiles stored in the `other-dockerfiles` directory. The action takes one parameter, which is a name of a subdirectory in `other-dockerfiles`. Currently there's just one, `targetcli-fb`. The action has no other triggers than workflow-dispatch. For now, the `targetcli-fb` docker image does not need to be rebuilt all that often - supposedly only when the dockerfile gets updated.
Second change is an addition of the `packages` subtest for checking the open-iscsi functionality. The test is based on steps outlined by @chewi in https://github.com/flatcar/scripts/pull/2261.
CI run for amd64: http://jenkins.infra.kinvolk.io:8080/job/container/job/test/26905/console
The CI was running with some extra modifications …
> Add action for building other docker images, add a test for open-iscsi

- kola/tests/misc/tpm.go
- platform/machine/unprivqemu/flight.go
This will only work from GRUB 2.12 onwards, so restrict to 4082+. I initially wanted to add this check to the existing tpmTest function, but that wouldn't allow me to restrict the version.
flatcar/scripts#2318 should be merged first.
I also fixed a small bug while I was at it.
I think this is my first time writing Go, be nice. :stuck_out_tongue: 
```
kola run --board=amd64-usr --platform=qemu-unpriv --qemu-firmware=flatcar_production_qemu_uefi_efi_code.fd --qemu-image=flatcar_production_qemu_uefi_image.img --debug cl.tpm.eventlog
```
I've run the above against an existing release image where it fails and my new [GRUB 2.12 image](https://bincache.flatcar-linux.net/images/amd64/9999.9.9+grub-2.12-1/flatcar_production_qemu_uefi_image.img) where it passes. I have also tried the Docker image …
> kola/tests: Add new cl.tpm.eventlog test for the TPM Event log

- README.md
- cmd/cork/downloadimage.go
- cmd/kola/options.go
- kola/tests/misc/update.go
- platform/qemu.go
Forthcoming Flatcar releases will use QCOW2 instead of raw .fd images.
Only pass SMM-related arguments to QEMU for amd64-usr. EDK2 doesn't have SMM for arm64 yet and these arguments break it when Secure Boot is enabled.
Skip tests that change the verity hash when Secure Boot is enabled. Changing the verity hash breaks Secure Boot verification, causing GRUB to error and then just sit at the menu forever. It's not clear why these tests worked before we applied the Red Hat patches to GRUB, but it's now behaving as it should.
Run tests against one of the new Flatcar Secure Boot builds.
Jenkins without qemu_uefi_secure is [all green](http://jenkins.infra.kinvolk.io:8080/job/container/job/sdk/1772/cldsv/). I'm running qemu_uefi_secure now.
> kola: cork: Handle QCOW2 EFI firmare images and fix arm64 Secure Boot

- kola/tests/misc/update.go
This reverts commit b583d18ffac499ddbcbcd7aa4b3da02903d19a9b. I misunderstood what these tests do. Booting is supposed to fail after changing the verity hash, but then it is supposed to successfully fall back to the other partition. The tests were failing due one of Red Hat's GRUB patches. We have now fixed this.
> Revert "kola/tests: Skip tests that change the verity hash when SB is enabled"

- kola/tests/kubeadm/kubeadm.go
- kola/tests/misc/cgroup1.go
Flatcar with systemd >= 256 does not support cgroupv1 anymore.
See: https://github.com/flatcar/scripts/pull/2145
> cgroupv1: do not run tests for version >= 4179

- Dockerfile
The azure-cli shipped with upstream Debian is hopelessly outdated and fails to perform basic tasks like launching VMs because it tries to talk to outdated APIs.
This change uses Microsoft's az-cli from MS Debian repositories, following https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt#option-1-install-with-one-command.
> Container image: use up-to-date azure-cli

- kola/tests/misc/nvidia.go
- kola/tests/util/devcontainer.go
- platform/api/aws/ec2.go
- platform/api/azure/instance.go
- platform/machine/aws/cluster.go
- platform/machine/azure/cluster.go
- platform/platform.go
- platform/qemu.go
- Add SkipFunc implementation for skipping test on unsupported instance types
- Add GPU operator test (includes nvidia-runtime sysext test)
- Add Arm64 support to both tests
- Add AWS support
> nvidia arm64 & GPU operator test

- Dockerfile
The warnings are appearing inside GitHub Actions about the inconsistent casing of keywords "from" and "as". Silence them.
> Dockerfile: Fix casing

- cmd/ore/azure/azure.go
- platform/api/azure/api.go
Missing ResourceGroupBasename in `ore` caused `ore` to have to process all rgs, also those missing the tags mantle expects. Ensure `ore azure gc` processes rgs that start with `kola-cluster` by default.
> fix ore azure segfault

- platform/api/azure/api.go
- platform/machine/azure/flight.go
Yet another follow-up for https://github.com/flatcar/mantle/pull/594 and https://github.com/flatcar/mantle/pull/588.
Plume prune/release/prerelease also fail. So rewire things to have a default value for resource group basename.
> platform/azure: Provide default for ResourceGroupBasename

- kola/tests/misc/nvidia.go
`nvidia-smi` path is swapped for sysext vs. non-sysext mode in the test
> kola/nvidia: Fix nvidia-smi path

- kola/tests/misc/verity.go
Otherwise `dd` can't read the kernel image.
Run CI with the change from flatcar/init#113.
With the other change, [CI has passed](http://jenkins.infra.kinvolk.io:8080/job/container/job/test/36707/cldsv/).
> kola/tests/misc/verity: /boot will only be readable by root so use sudo

- platform/api/azure/instance.go
- platform/machine/azure/cluster.go
Reorder error handling, such that when a VM creation times out, we don't clean it directly but try to fetch the serial console output before deletion. This can help debug OS provisioning timeout issues.
Provision a VM through kola with a broken ignition config, and observe that the console output ends up in the kola tmp directory.
> azure: Fetch console log from failed provisioning

- cli/cli.go
- platform/api/openstack/api.go
* long running tests end up hitting token expiry on openstack. enable reauth
* implement GC for keypairs. turns out they do export a "created_at" field. already executed.
* logging didn't work for ore commands because of how mantle set `PreRun()` functions. fixed this by calling `startLogging()` in the wrapper around a usersupplied function.
> openstack fixes

- kola/tests/kubeadm/kubeadm_test.go
- kola/tests/kubeadm/templates.go
- kola/tests/kubeadm/testdata.go
- kola/tests/kubeadm/testdata/kubeadmtestdatagen/README.md
- kola/tests/kubeadm/testdata/kubeadmtestdatagen/main.go
- kola/tests/kubeadm/testdata/master-calico-script.sh
- kola/tests/kubeadm/testdata/master-cilium-amd64-config.yml
- kola/tests/kubeadm/testdata/master-cilium-arm64-config.yml
- kola/tests/kubeadm/testdata/master-cilium-script.sh
- kola/tests/kubeadm/testdata/master-flannel-script.sh
- test
Noticed a warning about some config that was deprecated in k8s 1.31, which is the oldest version of k8s we test. Since it's safe to update, I did so. But when updating testdata I noticed two things. Updating the testdata manually is annoying and there is some weird whitespace in generated yaml files. I wrote the generator for the former, and updated the templates for the latter.
> Update kubeadm config to v1beta4, whitespace cleanups, testdata generator
