flatcar/mantle

cmd/cork/create.go
And flatcar-master as the default branch.
=> cork: use flatcar-linux repo for create

cmd/kola/options.go, cmd/ore/gcloud/gcloud.go
We are now using Flatcar's own GCE account. Switch to the new project.
=> kola,ore: change project name

cmd/plume/specs.go
Add a new channel `edge` for experimental features.
=> cmd/plume: add an edge channel

cmd/plume/README.md, cmd/plume/containerlinux.go, kola/tests/docker/docker.go, kola/tests/misc/grub.go, kola/tests/misc/update.go, kola/tests/misc/verity.go, kola/tests/rkt/rkt.go, sdk/enter.go
Update flatcar-master-edge to get it in sync with flatcar-master.
=> Merge flatcar-master to flatcar-master-edge 2019-11-26

kola/tests/misc/ntp.go
Since v243, systemd-timesyncd prints out its status message like this:
```
Initial synchronization to time server 10.0.0.1:123 (10.0.0.1).
```
So we need to deal with another case for that.
Let's create a list of possible output messages from systemd-timesyncd, so it can deal with possible systemd versions.
=> kola: adjust tests related to systemd-timesyncd for systemd >= v243

platform/machine/azure/flight.go
The cluster's resource group was used to store
the created image which caused it to be copied
again for each new cluster.
Use a separate resource group for the whole
flight to store the image for all clusters.
=> kola: Create Azure image for the whole flight

cmd/plume/prerelease.go
Because the image name used for the snapshot
was the same for amd64 and arm64, the first one
being published won and was reused.
Append a tag "-arm64" for arm64 images and
append " arm64" to the image description.
=> prerelease: Arch tag for EBS snapshot name

harness/harness.go
The TAP file is not useful if the console logs are lost because the
TAP files does not contain the error message.
Add a YAML description to the TAP file as understood by the Jenkins
TAP plugin. For now it only contains the test's error message as value
for the "Error" entry.
```
sshRetries = 5
sshTimeout = 5 * time.Second
$ make
$ cd bin
$ sudo ./kola run -d --qemu-skip-mangle --qemu-image flatcar_production_qemu_image.img
$ # while running and the first tests passed, corrupt the image file by overwriting it with a used one:
$ cp flatcar_production_qemu_image_something_that_got_booted_before.img flatcar_production_qemu_image.img
$ tail -f _kola_temp/qemu-latest/test.tap  # watch entries for passed and failed tests
1..57
ok - cl.ignition.v2_1.swap
not ok - cl.filesystem
---
Error: " …
```
=> kola: Add YAML description with error message to TAP file

kola/tests/coretest/core.go
We should also test more if symlinks for Flatcar exist.
* `/etc/coreos` - `/etc/flatcar`
* `/usr/bin/coreos-install` - `/usr/bin/flatcar-install`
* `/usr/lib/coreos` - `/usr/lib/flatcar`
* `/usr/share/coreos` - `/usr/share/flatcar`
For that, define a map that contains all the symlinks.
=> kola: add more tests for Flatcar symlinks

README.md
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
Click the link.
Clicked the link, compared to the previous page
=> README: point to flatcar docs

platform/platform.go
`CheckMachine` in `platform/platform.go` returns an error if one or multiple systemd unit(s) failed to start. While it prints the failed unit name it does not provide details on the failure.
This PR adds output from `systemctl status <unit>` and `journalctl -b -u <unit>` for a failed unit.
Run a test with `kola` using an OS image that fails to start a unit. The error output should provide details (from the journal) on the unit's failure.
Tested with a transient issue of `kubelet.service` to connect to `quay.io`, making the service fail in some test runs and succeed in others.
=> platform.go: add status and journal output to failed systemd units

sdk/repo/verify.go
Besides commit IDs and branches, the manifest can specify a revision
as tag via refs/tags/TAG.
Support manifests with tags when verifying with cork that the
repositories are in the desired state.
Create and build manifests with `refs/tags/TAG`
```
$EDITOR .repo/manifest.xml # modify the reference for afterburn to refs/tags/v0.1.0
cd src/third_party/afterburn
git checkout v0.1.0
cd -
~/kinvolk/mantle/bin/cork verify
cd -
git checkout flatcar-master
cd -
~/kinvolk/mantle/bin/cork verify
```
=> sdk/repo/verify: Support verifying that a tag was checked out

platform/platform.go
The CheckMachine functions waits until an SSH connection runs
"systemctl is-system-running" with an output like "running" or
"degraded". However, the error message always suggested that SSH
would be unable to connect because it only stated "ssh unreachable".
Extend the error message to include the case of the system not being
ready and give more context for the "systemctl is-system-running"
output if it failed.
Sometimes the error is encountered on Azure with: cl.etcd-member.discovery cl.locksmith.cluster cl.flannel.vxlan cl.flannel.udp
`make test` and reproduced the error for `cl.flannel.udp`:
```
--- FAIL: cl.flannel.udp (1527.51s)
harness.go:519: Cluster failed starting machines: machine "jenkins-azure-89872ce22c" failed basic checks: ssh unreachable or system not ready: failure …
```
=> Clarify SSH check error message for new machines

Jenkinsfile
Build mantle in Jenkins.
```
docker run --rm -it -v `pwd`:/usr/src/myapp -w /usr/src/myapp -e CGO_ENABLED=1 golang:1.15 ./build
docker run --rm -it -v `pwd`:/usr/src/myapp -w /usr/src/myapp -e CGO_ENABLED=1 golang:1.15 ./test
```
=> Jenkins: Build with Go 1.15

cmd/ore/gcloud/create-image.go
We need to add a license to our GCE images. This is supported by the API, but the create-image command was not passing it.
I've already uploaded a set of images with our license using this command and it worked fine.
=> cmd/ore: Add a license parameter to gcloud create-image

kola/README.md
Signed-off-by: Vincent Batts <vbatts@kinvolk.io>
=> kola: point to our own repo

cmd/cork/create.go, sdk/repo.go
Sometimes the git branches the manifest refers to should not be
changed but still a modification introduced. This can now be done
in the form of a patch file for each of the three repositories that
define what gets build. A single patch file is taken but "git am"
is able to process the concatenation of multiple files well. The
three-way merge option is set to be able to use slightly outdated
patches as long as they get merged automatically by git.
I created dummy patch files with `git format-patch -1` on top of `main` in each of my own external repositories and then updated an existing SDK to apply these patches after processing the manifest for `main`:
```
./cork update --scripts-patch ~/kinvolk/flatcar-scripts/0001-test.patch --overlay-patch …
```
=> cmd/cork: Allow to apply a patch on top of the manifest references

platform/qemu.go
The OEM partition can't be mounted more than once when it's a btrfs
filesystem, because having the same UUID is reserved for RAID usage.
When two kola instances run at the same time there is a possibility
for a race when both shortly want to use the OEM partition.
Use a conditional retry waiter to wait for exclusive access, giving
up after 10 minutes.
Run the qemu platform while also having the OEM partition mounted (`gnome-disk-image-mounter flatcar_production_image.bin`).
The waiter should get active until the OEM partition is unmounted with `gnome-disks`.
The above for the nightly alpha build.
=> platform/qemu: retry if OEM btrfs filesystem is in use

CHANGELOG.md
Maintain a CHANGELOG file for the releases.
Signed-off-by: Sayan Chowdhury <sayan@kinvolk.io>
=> Add CHANGELOG file for the 0.16.0 release

Jenkinsfile
With this change we no longer need the job parameter so it has been removed.
The arm64 build requires disabling 'CGO_ENABLED' as otherwise we would need a
cross-compiler in the build container. The arm64 artifacts are now archived at
bin.arm64. The build has also been switched to go1.16, this is what we are
using in the Flatcar SDK as well.
=> Jenkinsfile: also build arm64 artifacts

README.md
./build kola kolet
[ describe the change in 1 - 3 paragraphs ]
=> Misspelled word

CHANGELOG.md
=> changelog: bump to 0.18.0

kola/tests/ignition/execution.go
The ign-converter logic was broken for links that share a prefix but
don't actually use the link as part of the path. Also, we didn't have
Ignition link tests anyway.
Add an Ignition link test that also checks the prefix case.
Maybe merge it with another test?
[passed on the fixed build](http://jenkins.infra.kinvolk.io:8080/job/os/job/kola/job/qemu/3881/console) from https://github.com/flatcar-linux/coreos-overlay/pull/1710
=> kola: add cl.ignition.links tests

util/bunzip.go
Use lbunzip2 if the binary is available on the system. RIght now the os/prerelease/azure job takes much longer since we switched to fixed size VHDs.
Run an os/prerelease/azure job with MANTLE_JOB set to a build containing this commit.
Ran an os/prerelease/azure job with MANTLE_JOB set to a build containing this commit.
=> util/bunzip: use lbunzip2 if available

kola/tests/ignition/execution.go
Related-To: https://github.com/flatcar-linux/Flatcar/issues/812
<hr>
Locally tested.
=> test/ignition: add test for space escaping

platform/api/openstack/api.go
<hr>
OpenStack images will be created on the fly in the CI, we need to clean-up created images with `mantle` tags.
I don't think it needs a changelog entry - tested on the OpenStack setup.
=> os/api: add image deletion in the GC

cmd/plume/prerelease.go
The new build pipeline will copy the files itself to the release directory instead of using GCS.
Create local files that the new pipeline can upload.
The new pipeline can upload all local files with the common names as expected (`flatcar_production_ami_all.json` and `flatcar_production_ami_*.txt`)
None, will be validated when the pipeline is first used
=> plume: create AMI ID list files locally

cmd/plume/containerlinux.go
=> plume/release: define arch following the board

CHANGELOG.md, cmd/kola/options.go, kola/registry/registry.go, kola/tests/devcontainer/devcontainer.go, platform/machine/qemu/cluster.go, platform/machine/qemu/flight.go, platform/qemu.go
This is to have a dev container test in the new pipeline. It runs only on qemu.
=> kola/tests/devcontainer: New test

kola/harness.go, platform/api/azure/api.go, platform/api/azure/groups.go, platform/api/azure/image.go, platform/api/azure/instance.go, platform/api/azure/network.go, platform/api/azure/options.go, platform/api/azure/storage.go, platform/api/azure/storage_mit.go, platform/machine/azure/cluster.go, platform/machine/azure/flight.go, platform/machine/azure/machine.go
`userData` should be the new way to set user-data.
=> azure: set user-data on top of custom data

kola/tests/systemd/sysext.go
It allows to support tests in arm64 environment.
=> kola/sysext: add ARCH option to Docker sysext image creation

kola/tests/update/update.go
The cl.update.payload test can't run if the update payload isn't passed and gets skipped then. This was done after provisioning the test instance.
To save test time, evaluate the test condition in advance.
With CI
Test with CI
http://jenkins.infra.kinvolk.io:8080/job/container/job/test/6094/console
http://jenkins.infra.kinvolk.io:8080/job/container/job/test/6095/console
`kola list --filter` still shows it because the evaluation is done only after the first semver check instance is started
=> kola/tests: Evaluate skip condition before provisioning

kola/tests/update/update.go
For OEM sysext images and optional Flatcar extensions we need on-boot selection of the active sysext image and possible moving between the rootfs and the OEM partition. This is introduced in https://github.com/flatcar/bootengine/pull/50
Add a new test to check that the boot logic works as expected by preparing a QEMU machine to cover the relevant conditions. Since the systemd units in the initrd and the mounting is different depending on whether Ignition runs and itself interacts with the OEM partition, we have two machines, one without Ignition and one with because we anyway need to aquire the full version string first to be able to create the Ignition config with the right entries.
Only merge if https://github.com/flatcar/bootengine/pull/50 is merged and also adjust the major version …
=> kola: Add new cl.sysext.boot test for selection of active OEM sysext

kola/tests/misc/network.go
Systemd is at it again, changing some strings. Generalize the string search a bit and add new strings.
=> Update some journal strings for systemd 252

kola/tests/misc/state.go
The new flatcar-reset tool and boot logic for selective OS reset should allow to discard all local state except wanted paths that are to be preserved.
Add a test that checks if the OS reset works as expected.
With https://github.com/flatcar/coreos-overlay/pull/2483
Local run of `cl.osreset.ignition-rerun cl.overlay.cleanup`
=> kola/tests: Add test for OS reset

kola/tests/update/update.go
The sysext OEM download fallback logic is needed for cases where the OEM was deleted by the user or wasn't provided in the update process. Since this test depends on the build artifacts, it is made conditional to be skipped in, e.g., PR tests.
see https://github.com/flatcar/scripts/pull/906
=> kola: Add sysext OEM download test

platform/qemu.go
See: https://listman.redhat.com/archives/libvir-list/2021-February/msg00647.html
=> platform/qemu: Handle different tpm-tis device name on arm64

kola/tests/misc/tpm.go
The existing TPM tests use clevis. With systemd-cryptenroll and systemd-cryptsetup there are different features supported and the on-disk format in the LUKS data is also different. Add a cryptenroll test similar to the clevis test, but only for the rootfs.
```
--- PASS: cl.tpm.root-cryptenroll (45.20s)
```
=> kola: Add systemd-cryptenroll TPM2 test

Dockerfile
Last-ditch effort to work-around issues with docker image builds.
=> Dockerfile: Repeat apt-get several times until it succeeds

MAINTAINERS
The file is outdated, please refer to MAINTAINERS.md
=> Drop MAINTAINERS

kola/tests/misc/nvidia.go
We used to do it this way, then I moved the skipping to SkipFunc. Unfortunately this doesn't work well for vendor-testing/azure.sh in flatcar/scripts which passes 'cl.internet cl.misc.nvidia' to one GPU VM size and to one Gen1 VM size. It would be much more complex to straighten this out in bash, because the arguments are passed into other helper functions so restore runtime skipping.
Switch to creating the machine from the testcase (ClusterSize=0), so that the skip happens before the machine is created, saving time.
=> kola/nvidia: Skip tests at runtime

kola/tests/misc/raid.go, kola/tests/misc/tang.go, kola/tests/misc/tpm.go, kola/tests/sysext/zfs.go, kola/tests/util/devcontainer.go
It's a drive-by change I made while tinkering with the raid tests.
=> kola: Simplify NewMachineWithOptions usage

kola/tests/update/update.go
update: boot: add cl.update.payload-boot-part-too-small test case
This test case makes sure that the Flatcar upgrade fails if the
update payload contains an initrd that has a bigger size than the
free space in the /boot partition.
Currently, the /boot partition free space is around 70 MB.
This test case relies on cl.update.payload test case, but does an additional `sudo dd if=/dev/zero of=/boot/increase_boot_part_usage bs=5M count=1` before the update is started.
It also checks for the failure logs of the update-engine to appear in the journalctl output.
=> Add test case: cl.update.payload-boot-part-too-small
